# Generated by Django 4.1.3 on 2022-12-09 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(choices=[('banano', 'banano'), ('manzana', 'manzana'), ('papaya', 'papaya'), ('uvas', 'uvas'), ('mandarina', 'mandarina'), ('fresa', 'fresa')], max_length=254)),
                ('cantidad', models.CharField(choices=[('100 kgs', '100 kgs'), ('60 kgs', '60 kgs'), ('50 kgs', '50 kgs'), ('90 kgs', '90 kgs'), ('80 kgs', '80 kgs'), ('70 kgs', '70 kgs')], max_length=254)),
                ('precio_kgs', models.CharField(max_length=254)),
                ('precio_total', models.CharField(max_length=254)),
                ('ciudad', models.CharField(choices=[('facatativa', 'facatativa'), ('apartado', 'apartado'), ('arauca', 'arauca'), ('barranquilla', 'barranquilla'), ('cali', 'cali'), ('boyaca', 'boyaca'), ('magangue', 'magangue'), ('cucuta', 'cucuta'), ('girardot', 'girardot'), ('medellin', 'medellin'), ('zipaquira', 'zipaquira'), ('fusagasuga', 'fusagasuga'), ('cartagena', 'cartagena'), ('sabanalarga', 'sabanalarga'), ('rionegro', 'rionegro'), ('el carmen de bolivar', 'el carmen de bolivar'), ('bogota', 'bogota'), ('caucasia', 'caucasia'), ('turbo', 'turbo'), ('tunja', 'tunja'), ('leticia', 'leticia')], max_length=254)),
                ('fecha_disponible', models.CharField(max_length=254)),
                ('ofrece_transporte', models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], max_length=254)),
                ('descripcion', models.CharField(max_length=254)),
                ('estado', models.CharField(choices=[('Disponible', 'disponible'), ('no disponible', 'no disponible'), ('pendiente', 'pendiente')], max_length=254)),
            ],
            options={
                'db_table': 'inventario',
            },
        ),
        migrations.CreateModel(
            name='productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(choices=[('banano', 'banano'), ('manzana', 'manzana'), ('papaya', 'papaya'), ('uvas', 'uvas'), ('mandarina', 'mandarina'), ('fresa', 'fresa')], max_length=254)),
                ('cantidad', models.CharField(choices=[('100 kgs', '100 kgs'), ('60 kgs', '60 kgs'), ('50 kgs', '50 kgs'), ('90 kgs', '90 kgs'), ('80 kgs', '80 kgs'), ('70 kgs', '70 kgs')], max_length=254)),
                ('precio_kgs', models.CharField(max_length=254)),
                ('precio_total', models.CharField(max_length=254)),
                ('ciudad', models.CharField(choices=[('facatativa', 'facatativa'), ('apartado', 'apartado'), ('arauca', 'arauca'), ('barranquilla', 'barranquilla'), ('cali', 'cali'), ('boyaca', 'boyaca'), ('magangue', 'magangue'), ('cucuta', 'cucuta'), ('girardot', 'girardot'), ('medellin', 'medellin'), ('zipaquira', 'zipaquira'), ('fusagasuga', 'fusagasuga'), ('cartagena', 'cartagena'), ('sabanalarga', 'sabanalarga'), ('rionegro', 'rionegro'), ('el carmen de bolivar', 'el carmen de bolivar'), ('bogota', 'bogota'), ('caucasia', 'caucasia'), ('turbo', 'turbo'), ('tunja', 'tunja'), ('leticia', 'leticia')], max_length=254)),
                ('fecha_disponible', models.CharField(max_length=254)),
                ('ofrece_transporte', models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], max_length=254)),
                ('descripcion', models.CharField(max_length=254)),
                ('estado', models.CharField(choices=[('Disponible', 'disponible'), ('no disponible', 'no disponible'), ('pendiente', 'pendiente')], max_length=254)),
            ],
            options={
                'db_table': 'productos',
            },
        ),
        migrations.CreateModel(
            name='registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=254)),
                ('rol', models.CharField(choices=[('eres cliente', 'eres cliente'), ('eres conductor', 'eres conducto'), ('eres productor', 'eres productor')], max_length=254)),
                ('nombres', models.CharField(max_length=254)),
                ('apellidos', models.CharField(max_length=254)),
                ('cedula', models.CharField(max_length=254)),
                ('direcion', models.CharField(max_length=254)),
                ('telefono', models.CharField(max_length=254)),
                ('celular', models.CharField(max_length=254)),
                ('correo', models.CharField(max_length=254)),
                ('ciudad', models.CharField(choices=[('facatativa', 'facatativa'), ('apartado', 'apartado'), ('arauca', 'arauca'), ('barranquilla', 'barranquilla'), ('cali', 'cali'), ('boyaca', 'boyaca'), ('magangue', 'magangue'), ('cucuta', 'cucuta'), ('girardot', 'girardot'), ('medellin', 'medellin'), ('zipaquira', 'zipaquira'), ('fusagasuga', 'fusagasuga'), ('cartagena', 'cartagena'), ('sabanalarga', 'sabanalarga'), ('rionegro', 'rionegro'), ('el carmen de bolivar', 'el carmen de bolivar'), ('bogota', 'bogota'), ('caucasia', 'caucasia'), ('turbo', 'turbo'), ('tunja', 'tunja'), ('leticia', 'leticia')], max_length=40)),
            ],
            options={
                'db_table': 'registro',
            },
        ),
        migrations.CreateModel(
            name='soporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo', models.CharField(max_length=50)),
                ('comentario', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'soporte',
            },
        ),
        migrations.CreateModel(
            name='vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_vehiculo', models.CharField(choices=[('Doble troque', 'Doble troque'), ('Turbo', 'Turbo'), ('Tractomula 2 troques', 'Tractomula 2 troques'), ('Camion sencillo', 'Camion'), ('Luv', 'Luv'), ('Minimula', 'Minimula'), ('Cuatro manos', 'Cuatro manos'), ('Tractomula 3 troques', 'Tractomula 3 troques')], max_length=100)),
                ('tipo_carroceria', models.CharField(choices=[('termoquin', 'termoquin'), ('furgon', 'furgon'), ('platon', 'platon'), ('estacas', 'estacas')], max_length=100)),
                ('capacidad', models.CharField(choices=[('27_TONOLEDA', '27_TONOLEDA'), ('15_TONELADA', '15_TONELADA'), ('12_TONELADA', '12_TONELADA'), ('9_TONELADA', '9_TONELADA'), ('13_TONOLEDA', '13_TONOLEDA'), ('8_TONOLEDA', '8_TONOLEDA'), ('32_TONOLEDA', '32_TONOLEDA'), ('11_TONOLEDA', '11_TONOLEDA'), ('21_TONELADA', '21_TONELADA'), ('2_TONELADA', '2_TONELADA'), ('4_TONELADA', '4_TONELADA'), ('5_TONELADA', '5_TONELADA'), ('30_TONOLEDA', '30_TONOLEDA'), ('1_TONELADA', '1_TONELADA'), ('500_KGS', '500_KGS'), ('10_TONELADA', '10_TONELADA'), ('6_TONOLEDA', '6_TONOLEDA'), ('24_TONELADA', '24_TONELADA'), ('18_TONOLEDA', '18_TONOLEDA'), ('3_TONOLEDA', '3_TONOLEDA'), ('7_TONELADA', '7_TONELADA')], max_length=100)),
                ('marca', models.CharField(choices=[('KIA', '3_TONOLEDA'), ('CHEVROLET', '500_KGS'), ('TOYOTA', '4_TONELADA'), ('MAZDA', '1_TONELADA'), ('NISSAN', '6_TONOLEDA'), ('FORD', '2_TONELADA'), ('HIUNDAY', '5_TONELADA')], max_length=254)),
                ('modelo', models.CharField(max_length=4)),
                ('placa', models.CharField(max_length=6)),
                ('color', models.CharField(choices=[('azul', 'azul'), ('naranja', 'naranja'), ('rosado', 'rosado'), ('negro', 'negro'), ('gris', 'gris'), ('perlado', 'perlado'), ('amarillo', 'amarillo'), ('dorado', 'dorado'), ('blanco', 'blanco'), ('cafe', 'cafe'), ('morado', 'morado'), ('rojo', 'rojo')], max_length=100)),
            ],
            options={
                'db_table': 'vehiculo',
            },
        ),
    ]
