# Generated by Django 4.1.3 on 2022-11-17 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('identification_card', models.CharField(max_length=10)),
                ('direction', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=10)),
                ('cell_phone', models.CharField(max_length=11)),
                ('email', models.CharField(max_length=254)),
                ('city', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=254)),
            ],
            options={
                'db_table': 'cliente',
            },
        ),
        migrations.CreateModel(
            name='driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('identification_card', models.CharField(max_length=10)),
                ('direction', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=10)),
                ('cell_phone', models.CharField(max_length=11)),
                ('email', models.CharField(max_length=254)),
                ('vehicle_type', models.CharField(choices=[('Tractomula 3 troques', 'Tractomula 3 troques'), ('Camion sencillo', 'Camion'), ('Doble troque', 'Doble troque'), ('Cuatro manos', 'Cuatro manos'), ('Pickup', 'Pickup'), ('Turbo', 'Turbo'), ('Tractomula 2 troques', 'Tractomula 2 troques'), ('Luv', 'Luv'), ('Minimula', 'Minimula')], max_length=254, null=True)),
                ('city', models.CharField(max_length=50)),
                ('year', models.CharField(max_length=4)),
                ('password', models.CharField(max_length=254)),
            ],
            options={
                'db_table': 'driver',
            },
        ),
        migrations.CreateModel(
            name='producer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('identification_card', models.CharField(max_length=10)),
                ('direction', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=10)),
                ('cell_phone', models.CharField(max_length=11)),
                ('email', models.CharField(max_length=254)),
                ('city', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=254)),
            ],
            options={
                'db_table': 'productor',
            },
        ),
        migrations.CreateModel(
            name='tabla_prueba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('identification_card', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'tabla_prueba',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('usuario', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=254)),
            ],
        ),
    ]
