# Generated by Django 4.1.3 on 2022-12-11 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='abarrotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(choices=[], max_length=100)),
                ('cantidad', models.CharField(choices=[('50 kgs', '50 kgs'), ('100 kgs', '100 kgs'), ('80 kgs', '80 kgs'), ('70 kgs', '70 kgs'), ('60 kgs', '60 kgs'), ('90 kgs', '90 kgs')], max_length=100)),
                ('precio_kgs', models.CharField(max_length=100)),
                ('precio_total', models.CharField(max_length=100)),
                ('ciudad', models.CharField(choices=[('el carmen de bolivar', 'el carmen de bolivar'), ('arauca', 'arauca'), ('turbo', 'turbo'), ('cucuta', 'cucuta'), ('boyaca', 'boyaca'), ('fusagasuga', 'fusagasuga'), ('cartagena', 'cartagena'), ('medellin', 'medellin'), ('tunja', 'tunja'), ('facatativa', 'facatativa'), ('sabanalarga', 'sabanalarga'), ('magangue', 'magangue'), ('zipaquira', 'zipaquira'), ('bogota', 'bogota'), ('girardot', 'girardot'), ('caucasia', 'caucasia'), ('apartado', 'apartado'), ('cali', 'cali'), ('leticia', 'leticia'), ('barranquilla', 'barranquilla'), ('rionegro', 'rionegro')], max_length=50)),
                ('fecha_disponible', models.DateField(verbose_name='fecha disponible')),
                ('ofrece_transporte', models.CharField(choices=[('NO', 'NO'), ('SI', 'SI')], max_length=254)),
                ('descripcion', models.CharField(max_length=254)),
                ('estado', models.CharField(choices=[('pendiente', 'pendiente'), ('Disponible', 'disponible'), ('no disponible', 'no disponible')], max_length=50)),
            ],
            options={
                'db_table': 'abarrotes',
            },
        ),
        migrations.CreateModel(
            name='carnes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(choices=[], max_length=100)),
                ('cantidad', models.CharField(choices=[('50 kgs', '50 kgs'), ('100 kgs', '100 kgs'), ('80 kgs', '80 kgs'), ('70 kgs', '70 kgs'), ('60 kgs', '60 kgs'), ('90 kgs', '90 kgs')], max_length=100)),
                ('precio_kgs', models.CharField(max_length=100)),
                ('precio_total', models.CharField(max_length=100)),
                ('ciudad', models.CharField(choices=[('el carmen de bolivar', 'el carmen de bolivar'), ('arauca', 'arauca'), ('turbo', 'turbo'), ('cucuta', 'cucuta'), ('boyaca', 'boyaca'), ('fusagasuga', 'fusagasuga'), ('cartagena', 'cartagena'), ('medellin', 'medellin'), ('tunja', 'tunja'), ('facatativa', 'facatativa'), ('sabanalarga', 'sabanalarga'), ('magangue', 'magangue'), ('zipaquira', 'zipaquira'), ('bogota', 'bogota'), ('girardot', 'girardot'), ('caucasia', 'caucasia'), ('apartado', 'apartado'), ('cali', 'cali'), ('leticia', 'leticia'), ('barranquilla', 'barranquilla'), ('rionegro', 'rionegro')], max_length=50)),
                ('fecha_disponible', models.DateField(verbose_name='fecha disponible')),
                ('ofrece_transporte', models.CharField(choices=[('NO', 'NO'), ('SI', 'SI')], max_length=254)),
                ('descripcion', models.CharField(max_length=254)),
                ('estado', models.CharField(choices=[('pendiente', 'pendiente'), ('Disponible', 'disponible'), ('no disponible', 'no disponible')], max_length=50)),
            ],
            options={
                'db_table': 'carnes',
            },
        ),
        migrations.CreateModel(
            name='cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('cedula', models.CharField(max_length=9, unique=True)),
                ('direcion', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=10)),
                ('celular', models.CharField(max_length=10, unique=True)),
                ('correo', models.EmailField(max_length=100, unique=True)),
                ('ciudad', models.CharField(choices=[('el carmen de bolivar', 'el carmen de bolivar'), ('arauca', 'arauca'), ('turbo', 'turbo'), ('cucuta', 'cucuta'), ('boyaca', 'boyaca'), ('fusagasuga', 'fusagasuga'), ('cartagena', 'cartagena'), ('medellin', 'medellin'), ('tunja', 'tunja'), ('facatativa', 'facatativa'), ('sabanalarga', 'sabanalarga'), ('magangue', 'magangue'), ('zipaquira', 'zipaquira'), ('bogota', 'bogota'), ('girardot', 'girardot'), ('caucasia', 'caucasia'), ('apartado', 'apartado'), ('cali', 'cali'), ('leticia', 'leticia'), ('barranquilla', 'barranquilla'), ('rionegro', 'rionegro')], max_length=40)),
            ],
            options={
                'db_table': 'cliente',
            },
        ),
        migrations.CreateModel(
            name='frutas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(choices=[('papaya', 'papaya'), ('fresa', 'fresa'), ('limon', 'limon'), ('granadilla', 'granadilla'), ('banano', 'banano'), ('uva', 'uva'), ('pera', 'pera'), ('piña', 'piña'), ('manzana', 'manzana'), ('durazno', 'durazno'), ('mango', 'mango'), ('arandanos', 'arandanos'), ('kiwi', 'kiwi'), ('guanabana', 'guanabana'), ('maracuya', 'maracuya'), ('mandarina', 'mandarina'), ('ciruela', 'ciruela'), ('cereza', 'cereza'), ('naranja', 'naranja'), ('sandia', 'sandia'), ('mora', 'mora'), ('pitaya', 'pitaya'), ('frambueza', 'frambueza'), ('melon', 'melon'), ('uvas', 'uvas')], max_length=100)),
                ('cantidad', models.CharField(choices=[('50 kgs', '50 kgs'), ('100 kgs', '100 kgs'), ('80 kgs', '80 kgs'), ('70 kgs', '70 kgs'), ('60 kgs', '60 kgs'), ('90 kgs', '90 kgs')], max_length=100)),
                ('precio_kgs', models.CharField(max_length=100)),
                ('precio_total', models.CharField(max_length=100)),
                ('ciudad', models.CharField(choices=[('el carmen de bolivar', 'el carmen de bolivar'), ('arauca', 'arauca'), ('turbo', 'turbo'), ('cucuta', 'cucuta'), ('boyaca', 'boyaca'), ('fusagasuga', 'fusagasuga'), ('cartagena', 'cartagena'), ('medellin', 'medellin'), ('tunja', 'tunja'), ('facatativa', 'facatativa'), ('sabanalarga', 'sabanalarga'), ('magangue', 'magangue'), ('zipaquira', 'zipaquira'), ('bogota', 'bogota'), ('girardot', 'girardot'), ('caucasia', 'caucasia'), ('apartado', 'apartado'), ('cali', 'cali'), ('leticia', 'leticia'), ('barranquilla', 'barranquilla'), ('rionegro', 'rionegro')], max_length=50)),
                ('fecha_disponible', models.DateField(verbose_name='fecha disponible')),
                ('ofrece_transporte', models.CharField(choices=[('NO', 'NO'), ('SI', 'SI')], max_length=254)),
                ('descripcion', models.CharField(max_length=254)),
                ('estado', models.CharField(choices=[('pendiente', 'pendiente'), ('Disponible', 'disponible'), ('no disponible', 'no disponible')], max_length=50)),
            ],
            options={
                'db_table': 'frutas',
            },
        ),
        migrations.CreateModel(
            name='granos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(choices=[], max_length=100)),
                ('cantidad', models.CharField(choices=[('50 kgs', '50 kgs'), ('100 kgs', '100 kgs'), ('80 kgs', '80 kgs'), ('70 kgs', '70 kgs'), ('60 kgs', '60 kgs'), ('90 kgs', '90 kgs')], max_length=100)),
                ('precio_kgs', models.CharField(max_length=100)),
                ('precio_total', models.CharField(max_length=100)),
                ('ciudad', models.CharField(choices=[('el carmen de bolivar', 'el carmen de bolivar'), ('arauca', 'arauca'), ('turbo', 'turbo'), ('cucuta', 'cucuta'), ('boyaca', 'boyaca'), ('fusagasuga', 'fusagasuga'), ('cartagena', 'cartagena'), ('medellin', 'medellin'), ('tunja', 'tunja'), ('facatativa', 'facatativa'), ('sabanalarga', 'sabanalarga'), ('magangue', 'magangue'), ('zipaquira', 'zipaquira'), ('bogota', 'bogota'), ('girardot', 'girardot'), ('caucasia', 'caucasia'), ('apartado', 'apartado'), ('cali', 'cali'), ('leticia', 'leticia'), ('barranquilla', 'barranquilla'), ('rionegro', 'rionegro')], max_length=50)),
                ('fecha_disponible', models.DateField(verbose_name='fecha disponible')),
                ('ofrece_transporte', models.CharField(choices=[('NO', 'NO'), ('SI', 'SI')], max_length=254)),
                ('descripcion', models.CharField(max_length=254)),
                ('estado', models.CharField(choices=[('pendiente', 'pendiente'), ('Disponible', 'disponible'), ('no disponible', 'no disponible')], max_length=50)),
            ],
            options={
                'db_table': 'granos',
            },
        ),
        migrations.CreateModel(
            name='inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(choices=[('papaya', 'papaya'), ('fresa', 'fresa'), ('limon', 'limon'), ('granadilla', 'granadilla'), ('banano', 'banano'), ('uva', 'uva'), ('pera', 'pera'), ('piña', 'piña'), ('manzana', 'manzana'), ('durazno', 'durazno'), ('mango', 'mango'), ('arandanos', 'arandanos'), ('kiwi', 'kiwi'), ('guanabana', 'guanabana'), ('maracuya', 'maracuya'), ('mandarina', 'mandarina'), ('ciruela', 'ciruela'), ('cereza', 'cereza'), ('naranja', 'naranja'), ('sandia', 'sandia'), ('mora', 'mora'), ('pitaya', 'pitaya'), ('frambueza', 'frambueza'), ('melon', 'melon'), ('uvas', 'uvas')], max_length=254)),
                ('cantidad', models.CharField(choices=[('50 kgs', '50 kgs'), ('100 kgs', '100 kgs'), ('80 kgs', '80 kgs'), ('70 kgs', '70 kgs'), ('60 kgs', '60 kgs'), ('90 kgs', '90 kgs')], max_length=254)),
                ('precio_kgs', models.CharField(max_length=254)),
                ('precio_total', models.CharField(max_length=254)),
                ('ciudad', models.CharField(choices=[('el carmen de bolivar', 'el carmen de bolivar'), ('arauca', 'arauca'), ('turbo', 'turbo'), ('cucuta', 'cucuta'), ('boyaca', 'boyaca'), ('fusagasuga', 'fusagasuga'), ('cartagena', 'cartagena'), ('medellin', 'medellin'), ('tunja', 'tunja'), ('facatativa', 'facatativa'), ('sabanalarga', 'sabanalarga'), ('magangue', 'magangue'), ('zipaquira', 'zipaquira'), ('bogota', 'bogota'), ('girardot', 'girardot'), ('caucasia', 'caucasia'), ('apartado', 'apartado'), ('cali', 'cali'), ('leticia', 'leticia'), ('barranquilla', 'barranquilla'), ('rionegro', 'rionegro')], max_length=254)),
                ('fecha_disponible', models.CharField(max_length=254)),
                ('ofrece_transporte', models.CharField(choices=[('NO', 'NO'), ('SI', 'SI')], max_length=254)),
                ('descripcion', models.CharField(max_length=254)),
                ('estado', models.CharField(choices=[('pendiente', 'pendiente'), ('Disponible', 'disponible'), ('no disponible', 'no disponible')], max_length=254)),
            ],
            options={
                'db_table': 'inventario',
            },
        ),
        migrations.CreateModel(
            name='lacteos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(choices=[], max_length=100)),
                ('cantidad', models.CharField(choices=[('50 kgs', '50 kgs'), ('100 kgs', '100 kgs'), ('80 kgs', '80 kgs'), ('70 kgs', '70 kgs'), ('60 kgs', '60 kgs'), ('90 kgs', '90 kgs')], max_length=100)),
                ('precio_kgs', models.CharField(max_length=100)),
                ('precio_total', models.CharField(max_length=100)),
                ('ciudad', models.CharField(choices=[('el carmen de bolivar', 'el carmen de bolivar'), ('arauca', 'arauca'), ('turbo', 'turbo'), ('cucuta', 'cucuta'), ('boyaca', 'boyaca'), ('fusagasuga', 'fusagasuga'), ('cartagena', 'cartagena'), ('medellin', 'medellin'), ('tunja', 'tunja'), ('facatativa', 'facatativa'), ('sabanalarga', 'sabanalarga'), ('magangue', 'magangue'), ('zipaquira', 'zipaquira'), ('bogota', 'bogota'), ('girardot', 'girardot'), ('caucasia', 'caucasia'), ('apartado', 'apartado'), ('cali', 'cali'), ('leticia', 'leticia'), ('barranquilla', 'barranquilla'), ('rionegro', 'rionegro')], max_length=50)),
                ('fecha_disponible', models.DateField(verbose_name='fecha disponible')),
                ('ofrece_transporte', models.CharField(choices=[('NO', 'NO'), ('SI', 'SI')], max_length=254)),
                ('descripcion', models.CharField(max_length=254)),
                ('estado', models.CharField(choices=[('pendiente', 'pendiente'), ('Disponible', 'disponible'), ('no disponible', 'no disponible')], max_length=50)),
            ],
            options={
                'db_table': 'lacteos',
            },
        ),
        migrations.CreateModel(
            name='leguminosas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(choices=[], max_length=100)),
                ('cantidad', models.CharField(choices=[('50 kgs', '50 kgs'), ('100 kgs', '100 kgs'), ('80 kgs', '80 kgs'), ('70 kgs', '70 kgs'), ('60 kgs', '60 kgs'), ('90 kgs', '90 kgs')], max_length=100)),
                ('precio_kgs', models.CharField(max_length=100)),
                ('precio_total', models.CharField(max_length=100)),
                ('ciudad', models.CharField(choices=[('el carmen de bolivar', 'el carmen de bolivar'), ('arauca', 'arauca'), ('turbo', 'turbo'), ('cucuta', 'cucuta'), ('boyaca', 'boyaca'), ('fusagasuga', 'fusagasuga'), ('cartagena', 'cartagena'), ('medellin', 'medellin'), ('tunja', 'tunja'), ('facatativa', 'facatativa'), ('sabanalarga', 'sabanalarga'), ('magangue', 'magangue'), ('zipaquira', 'zipaquira'), ('bogota', 'bogota'), ('girardot', 'girardot'), ('caucasia', 'caucasia'), ('apartado', 'apartado'), ('cali', 'cali'), ('leticia', 'leticia'), ('barranquilla', 'barranquilla'), ('rionegro', 'rionegro')], max_length=50)),
                ('fecha_disponible', models.DateField(verbose_name='fecha disponible')),
                ('ofrece_transporte', models.CharField(choices=[('NO', 'NO'), ('SI', 'SI')], max_length=254)),
                ('descripcion', models.CharField(max_length=254)),
                ('estado', models.CharField(choices=[('pendiente', 'pendiente'), ('Disponible', 'disponible'), ('no disponible', 'no disponible')], max_length=50)),
            ],
            options={
                'db_table': 'leguminosas',
            },
        ),
        migrations.CreateModel(
            name='Productor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('cedula', models.CharField(max_length=9, unique=True)),
                ('direcion', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=10)),
                ('celular', models.CharField(max_length=10, unique=True)),
                ('correo', models.EmailField(max_length=100, unique=True)),
                ('ciudad', models.CharField(choices=[('el carmen de bolivar', 'el carmen de bolivar'), ('arauca', 'arauca'), ('turbo', 'turbo'), ('cucuta', 'cucuta'), ('boyaca', 'boyaca'), ('fusagasuga', 'fusagasuga'), ('cartagena', 'cartagena'), ('medellin', 'medellin'), ('tunja', 'tunja'), ('facatativa', 'facatativa'), ('sabanalarga', 'sabanalarga'), ('magangue', 'magangue'), ('zipaquira', 'zipaquira'), ('bogota', 'bogota'), ('girardot', 'girardot'), ('caucasia', 'caucasia'), ('apartado', 'apartado'), ('cali', 'cali'), ('leticia', 'leticia'), ('barranquilla', 'barranquilla'), ('rionegro', 'rionegro')], max_length=40)),
            ],
            options={
                'db_table': 'productor',
            },
        ),
        migrations.CreateModel(
            name='productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(choices=[('papaya', 'papaya'), ('fresa', 'fresa'), ('limon', 'limon'), ('granadilla', 'granadilla'), ('banano', 'banano'), ('uva', 'uva'), ('pera', 'pera'), ('piña', 'piña'), ('manzana', 'manzana'), ('durazno', 'durazno'), ('mango', 'mango'), ('arandanos', 'arandanos'), ('kiwi', 'kiwi'), ('guanabana', 'guanabana'), ('maracuya', 'maracuya'), ('mandarina', 'mandarina'), ('ciruela', 'ciruela'), ('cereza', 'cereza'), ('naranja', 'naranja'), ('sandia', 'sandia'), ('mora', 'mora'), ('pitaya', 'pitaya'), ('frambueza', 'frambueza'), ('melon', 'melon'), ('uvas', 'uvas')], max_length=254)),
                ('cantidad', models.CharField(choices=[('50 kgs', '50 kgs'), ('100 kgs', '100 kgs'), ('80 kgs', '80 kgs'), ('70 kgs', '70 kgs'), ('60 kgs', '60 kgs'), ('90 kgs', '90 kgs')], max_length=254)),
                ('precio_kgs', models.CharField(max_length=254)),
                ('precio_total', models.CharField(max_length=254)),
                ('ciudad', models.CharField(choices=[('el carmen de bolivar', 'el carmen de bolivar'), ('arauca', 'arauca'), ('turbo', 'turbo'), ('cucuta', 'cucuta'), ('boyaca', 'boyaca'), ('fusagasuga', 'fusagasuga'), ('cartagena', 'cartagena'), ('medellin', 'medellin'), ('tunja', 'tunja'), ('facatativa', 'facatativa'), ('sabanalarga', 'sabanalarga'), ('magangue', 'magangue'), ('zipaquira', 'zipaquira'), ('bogota', 'bogota'), ('girardot', 'girardot'), ('caucasia', 'caucasia'), ('apartado', 'apartado'), ('cali', 'cali'), ('leticia', 'leticia'), ('barranquilla', 'barranquilla'), ('rionegro', 'rionegro')], max_length=254)),
                ('fecha_disponible', models.CharField(max_length=254)),
                ('ofrece_transporte', models.CharField(choices=[('NO', 'NO'), ('SI', 'SI')], max_length=254)),
                ('descripcion', models.CharField(max_length=254)),
                ('estado', models.CharField(choices=[('pendiente', 'pendiente'), ('Disponible', 'disponible'), ('no disponible', 'no disponible')], max_length=254)),
            ],
            options={
                'db_table': 'productos',
            },
        ),
        migrations.CreateModel(
            name='registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('cedula', models.CharField(max_length=9, unique=True)),
                ('direcion', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=10)),
                ('celular', models.CharField(max_length=10, unique=True)),
                ('correo', models.CharField(max_length=100, unique=True)),
                ('ciudad', models.CharField(choices=[('el carmen de bolivar', 'el carmen de bolivar'), ('arauca', 'arauca'), ('turbo', 'turbo'), ('cucuta', 'cucuta'), ('boyaca', 'boyaca'), ('fusagasuga', 'fusagasuga'), ('cartagena', 'cartagena'), ('medellin', 'medellin'), ('tunja', 'tunja'), ('facatativa', 'facatativa'), ('sabanalarga', 'sabanalarga'), ('magangue', 'magangue'), ('zipaquira', 'zipaquira'), ('bogota', 'bogota'), ('girardot', 'girardot'), ('caucasia', 'caucasia'), ('apartado', 'apartado'), ('cali', 'cali'), ('leticia', 'leticia'), ('barranquilla', 'barranquilla'), ('rionegro', 'rionegro')], max_length=40)),
            ],
            options={
                'db_table': 'registro',
            },
        ),
        migrations.CreateModel(
            name='soporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo', models.CharField(max_length=50)),
                ('comentario', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'soporte',
            },
        ),
        migrations.CreateModel(
            name='verduras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(choices=[('brocoli', 'brocoli'), ('repollo', 'repollo'), ('aguacate', 'aguacate'), ('rabano', 'rabano'), ('acelga', 'acelga'), ('berenjena', 'berenjena'), ('zukini', 'zukini'), ('cilantro', 'cilantro'), ('arbeja', 'arbeja'), ('ahuyama', 'ahuyama'), ('habichuela', 'habichuela'), ('bruselas', 'bruselas'), ('coliflor', 'coliflor'), ('cebolla larga', 'cebolla larga'), ('remolacha', 'remolacha'), ('espinaca', 'espinaca'), ('pimenton', 'pimenton'), ('pepino', 'pepino'), ('zanahoria', 'zanahoria'), ('champiñon', 'champiñon'), ('tomate', 'tomate'), ('lechuga', 'lechuga'), ('apio', 'apio'), ('cebolla cabezona', 'cebolla cabezona')], max_length=100)),
                ('cantidad', models.CharField(choices=[('50 kgs', '50 kgs'), ('100 kgs', '100 kgs'), ('80 kgs', '80 kgs'), ('70 kgs', '70 kgs'), ('60 kgs', '60 kgs'), ('90 kgs', '90 kgs')], max_length=100)),
                ('precio_kgs', models.CharField(max_length=100)),
                ('precio_total', models.CharField(max_length=100)),
                ('ciudad', models.CharField(choices=[('el carmen de bolivar', 'el carmen de bolivar'), ('arauca', 'arauca'), ('turbo', 'turbo'), ('cucuta', 'cucuta'), ('boyaca', 'boyaca'), ('fusagasuga', 'fusagasuga'), ('cartagena', 'cartagena'), ('medellin', 'medellin'), ('tunja', 'tunja'), ('facatativa', 'facatativa'), ('sabanalarga', 'sabanalarga'), ('magangue', 'magangue'), ('zipaquira', 'zipaquira'), ('bogota', 'bogota'), ('girardot', 'girardot'), ('caucasia', 'caucasia'), ('apartado', 'apartado'), ('cali', 'cali'), ('leticia', 'leticia'), ('barranquilla', 'barranquilla'), ('rionegro', 'rionegro')], max_length=50)),
                ('fecha_disponible', models.DateField(verbose_name='fecha disponible')),
                ('ofrece_transporte', models.CharField(choices=[('NO', 'NO'), ('SI', 'SI')], max_length=254)),
                ('descripcion', models.CharField(max_length=254)),
                ('estado', models.CharField(choices=[('pendiente', 'pendiente'), ('Disponible', 'disponible'), ('no disponible', 'no disponible')], max_length=50)),
            ],
            options={
                'db_table': 'verduras',
            },
        ),
    ]
