# Generated by Django 4.1.3 on 2022-12-11 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='conductor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('cedula', models.CharField(max_length=9, unique=True)),
                ('direcion', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=10)),
                ('celular', models.CharField(max_length=10, unique=True)),
                ('correo', models.EmailField(max_length=100, unique=True)),
                ('ciudad', models.CharField(choices=[('rionegro', 'rionegro'), ('arauca', 'arauca'), ('el carmen de bolivar', 'el carmen de bolivar'), ('medellin', 'medellin'), ('sabanalarga', 'sabanalarga'), ('cartagena', 'cartagena'), ('facatativa', 'facatativa'), ('cali', 'cali'), ('cucuta', 'cucuta'), ('boyaca', 'boyaca'), ('bogota', 'bogota'), ('apartado', 'apartado'), ('magangue', 'magangue'), ('leticia', 'leticia'), ('fusagasuga', 'fusagasuga'), ('tunja', 'tunja'), ('caucasia', 'caucasia'), ('turbo', 'turbo'), ('girardot', 'girardot'), ('zipaquira', 'zipaquira'), ('barranquilla', 'barranquilla')], max_length=40)),
            ],
            options={
                'db_table': 'conductor',
            },
        ),
        migrations.CreateModel(
            name='vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_vehiculo', models.CharField(choices=[('Cuatro manos', 'Cuatro manos'), ('Turbo', 'Turbo'), ('Camion sencillo', 'Camion sencillo'), ('Camion grande', 'Camion grande'), ('Doble troque', 'Doble troque'), ('Minimula', 'Minimula'), ('Tractomula 2 troques', 'Tractomula 2 troques'), ('Tractomula 3 troques', 'Tractomula 3 troques'), ('Luv', 'Luv')], max_length=100)),
                ('tipo_carroceria', models.CharField(choices=[('estacas', 'estacas'), ('termoquin', 'termoquin'), ('furgon', 'furgon'), ('platon', 'platon')], max_length=100)),
                ('capacidad', models.CharField(choices=[('6_TONOLEDA', '6_TONOLEDA'), ('32_TONOLEDA', '32_TONOLEDA'), ('11_TONOLEDA', '11_TONOLEDA'), ('10_TONELADA', '10_TONELADA'), ('8_TONOLEDA', '8_TONOLEDA'), ('3_TONOLEDA', '3_TONOLEDA'), ('15_TONELADA', '15_TONELADA'), ('1_TONELADA', '1_TONELADA'), ('13_TONOLEDA', '13_TONOLEDA'), ('24_TONELADA', '24_TONELADA'), ('500_KGS', '500_KGS'), ('12_TONELADA', '12_TONELADA'), ('21_TONELADA', '21_TONELADA'), ('7_TONELADA', '7_TONELADA'), ('5_TONELADA', '5_TONELADA'), ('4_TONELADA', '4_TONELADA'), ('30_TONOLEDA', '30_TONOLEDA'), ('18_TONOLEDA', '18_TONOLEDA'), ('2_TONELADA', '2_TONELADA'), ('9_TONELADA', '9_TONELADA'), ('27_TONOLEDA', '27_TONOLEDA')], max_length=100)),
                ('marca', models.CharField(choices=[('MAZDA', 'MAZDA'), ('HIUNDAY', 'HIUNDAY'), ('FORD', 'FORD'), ('NISSAN', 'NISSAN'), ('TOYOTA', 'TOYOTA'), ('KIA', 'KIA'), ('CHEVROLET', 'CHEVROLET')], max_length=254)),
                ('modelo', models.CharField(max_length=4)),
                ('placa', models.CharField(max_length=6, unique=True)),
                ('color', models.CharField(choices=[('amarillo', 'amarillo'), ('azul', 'azul'), ('negro', 'negro'), ('naranja', 'naranja'), ('cafe', 'cafe'), ('rojo', 'rojo'), ('blanco', 'blanco'), ('dorado', 'dorado'), ('perlado', 'perlado'), ('gris', 'gris'), ('morado', 'morado'), ('rosado', 'rosado')], max_length=100)),
            ],
            options={
                'db_table': 'vehiculo',
            },
        ),
        migrations.AlterField(
            model_name='abarrotes',
            name='cantidad',
            field=models.CharField(choices=[('90 kgs', '90 kgs'), ('80 kgs', '80 kgs'), ('100 kgs', '100 kgs'), ('60 kgs', '60 kgs'), ('50 kgs', '50 kgs'), ('70 kgs', '70 kgs')], max_length=100),
        ),
        migrations.AlterField(
            model_name='abarrotes',
            name='ciudad',
            field=models.CharField(choices=[('rionegro', 'rionegro'), ('arauca', 'arauca'), ('el carmen de bolivar', 'el carmen de bolivar'), ('medellin', 'medellin'), ('sabanalarga', 'sabanalarga'), ('cartagena', 'cartagena'), ('facatativa', 'facatativa'), ('cali', 'cali'), ('cucuta', 'cucuta'), ('boyaca', 'boyaca'), ('bogota', 'bogota'), ('apartado', 'apartado'), ('magangue', 'magangue'), ('leticia', 'leticia'), ('fusagasuga', 'fusagasuga'), ('tunja', 'tunja'), ('caucasia', 'caucasia'), ('turbo', 'turbo'), ('girardot', 'girardot'), ('zipaquira', 'zipaquira'), ('barranquilla', 'barranquilla')], max_length=50),
        ),
        migrations.AlterField(
            model_name='abarrotes',
            name='estado',
            field=models.CharField(choices=[('Disponible', 'disponible'), ('no disponible', 'no disponible'), ('pendiente', 'pendiente')], max_length=50),
        ),
        migrations.AlterField(
            model_name='abarrotes',
            name='ofrece_transporte',
            field=models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], max_length=254),
        ),
        migrations.AlterField(
            model_name='carnes',
            name='cantidad',
            field=models.CharField(choices=[('90 kgs', '90 kgs'), ('80 kgs', '80 kgs'), ('100 kgs', '100 kgs'), ('60 kgs', '60 kgs'), ('50 kgs', '50 kgs'), ('70 kgs', '70 kgs')], max_length=100),
        ),
        migrations.AlterField(
            model_name='carnes',
            name='ciudad',
            field=models.CharField(choices=[('rionegro', 'rionegro'), ('arauca', 'arauca'), ('el carmen de bolivar', 'el carmen de bolivar'), ('medellin', 'medellin'), ('sabanalarga', 'sabanalarga'), ('cartagena', 'cartagena'), ('facatativa', 'facatativa'), ('cali', 'cali'), ('cucuta', 'cucuta'), ('boyaca', 'boyaca'), ('bogota', 'bogota'), ('apartado', 'apartado'), ('magangue', 'magangue'), ('leticia', 'leticia'), ('fusagasuga', 'fusagasuga'), ('tunja', 'tunja'), ('caucasia', 'caucasia'), ('turbo', 'turbo'), ('girardot', 'girardot'), ('zipaquira', 'zipaquira'), ('barranquilla', 'barranquilla')], max_length=50),
        ),
        migrations.AlterField(
            model_name='carnes',
            name='estado',
            field=models.CharField(choices=[('Disponible', 'disponible'), ('no disponible', 'no disponible'), ('pendiente', 'pendiente')], max_length=50),
        ),
        migrations.AlterField(
            model_name='carnes',
            name='ofrece_transporte',
            field=models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], max_length=254),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='ciudad',
            field=models.CharField(choices=[('rionegro', 'rionegro'), ('arauca', 'arauca'), ('el carmen de bolivar', 'el carmen de bolivar'), ('medellin', 'medellin'), ('sabanalarga', 'sabanalarga'), ('cartagena', 'cartagena'), ('facatativa', 'facatativa'), ('cali', 'cali'), ('cucuta', 'cucuta'), ('boyaca', 'boyaca'), ('bogota', 'bogota'), ('apartado', 'apartado'), ('magangue', 'magangue'), ('leticia', 'leticia'), ('fusagasuga', 'fusagasuga'), ('tunja', 'tunja'), ('caucasia', 'caucasia'), ('turbo', 'turbo'), ('girardot', 'girardot'), ('zipaquira', 'zipaquira'), ('barranquilla', 'barranquilla')], max_length=40),
        ),
        migrations.AlterField(
            model_name='frutas',
            name='cantidad',
            field=models.CharField(choices=[('90 kgs', '90 kgs'), ('80 kgs', '80 kgs'), ('100 kgs', '100 kgs'), ('60 kgs', '60 kgs'), ('50 kgs', '50 kgs'), ('70 kgs', '70 kgs')], max_length=100),
        ),
        migrations.AlterField(
            model_name='frutas',
            name='ciudad',
            field=models.CharField(choices=[('rionegro', 'rionegro'), ('arauca', 'arauca'), ('el carmen de bolivar', 'el carmen de bolivar'), ('medellin', 'medellin'), ('sabanalarga', 'sabanalarga'), ('cartagena', 'cartagena'), ('facatativa', 'facatativa'), ('cali', 'cali'), ('cucuta', 'cucuta'), ('boyaca', 'boyaca'), ('bogota', 'bogota'), ('apartado', 'apartado'), ('magangue', 'magangue'), ('leticia', 'leticia'), ('fusagasuga', 'fusagasuga'), ('tunja', 'tunja'), ('caucasia', 'caucasia'), ('turbo', 'turbo'), ('girardot', 'girardot'), ('zipaquira', 'zipaquira'), ('barranquilla', 'barranquilla')], max_length=50),
        ),
        migrations.AlterField(
            model_name='frutas',
            name='estado',
            field=models.CharField(choices=[('Disponible', 'disponible'), ('no disponible', 'no disponible'), ('pendiente', 'pendiente')], max_length=50),
        ),
        migrations.AlterField(
            model_name='frutas',
            name='ofrece_transporte',
            field=models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], max_length=254),
        ),
        migrations.AlterField(
            model_name='frutas',
            name='producto',
            field=models.CharField(choices=[('piña', 'piña'), ('manzana', 'manzana'), ('mandarina', 'mandarina'), ('sandia', 'sandia'), ('uva', 'uva'), ('kiwi', 'kiwi'), ('guanabana', 'guanabana'), ('cereza', 'cereza'), ('frambueza', 'frambueza'), ('maracuya', 'maracuya'), ('banano', 'banano'), ('papaya', 'papaya'), ('durazno', 'durazno'), ('melon', 'melon'), ('pera', 'pera'), ('arandanos', 'arandanos'), ('granadilla', 'granadilla'), ('uvas', 'uvas'), ('naranja', 'naranja'), ('ciruela', 'ciruela'), ('limon', 'limon'), ('mora', 'mora'), ('mango', 'mango'), ('pitaya', 'pitaya'), ('fresa', 'fresa')], max_length=100),
        ),
        migrations.AlterField(
            model_name='granos',
            name='cantidad',
            field=models.CharField(choices=[('90 kgs', '90 kgs'), ('80 kgs', '80 kgs'), ('100 kgs', '100 kgs'), ('60 kgs', '60 kgs'), ('50 kgs', '50 kgs'), ('70 kgs', '70 kgs')], max_length=100),
        ),
        migrations.AlterField(
            model_name='granos',
            name='ciudad',
            field=models.CharField(choices=[('rionegro', 'rionegro'), ('arauca', 'arauca'), ('el carmen de bolivar', 'el carmen de bolivar'), ('medellin', 'medellin'), ('sabanalarga', 'sabanalarga'), ('cartagena', 'cartagena'), ('facatativa', 'facatativa'), ('cali', 'cali'), ('cucuta', 'cucuta'), ('boyaca', 'boyaca'), ('bogota', 'bogota'), ('apartado', 'apartado'), ('magangue', 'magangue'), ('leticia', 'leticia'), ('fusagasuga', 'fusagasuga'), ('tunja', 'tunja'), ('caucasia', 'caucasia'), ('turbo', 'turbo'), ('girardot', 'girardot'), ('zipaquira', 'zipaquira'), ('barranquilla', 'barranquilla')], max_length=50),
        ),
        migrations.AlterField(
            model_name='granos',
            name='estado',
            field=models.CharField(choices=[('Disponible', 'disponible'), ('no disponible', 'no disponible'), ('pendiente', 'pendiente')], max_length=50),
        ),
        migrations.AlterField(
            model_name='granos',
            name='ofrece_transporte',
            field=models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], max_length=254),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='cantidad',
            field=models.CharField(choices=[('90 kgs', '90 kgs'), ('80 kgs', '80 kgs'), ('100 kgs', '100 kgs'), ('60 kgs', '60 kgs'), ('50 kgs', '50 kgs'), ('70 kgs', '70 kgs')], max_length=254),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='ciudad',
            field=models.CharField(choices=[('rionegro', 'rionegro'), ('arauca', 'arauca'), ('el carmen de bolivar', 'el carmen de bolivar'), ('medellin', 'medellin'), ('sabanalarga', 'sabanalarga'), ('cartagena', 'cartagena'), ('facatativa', 'facatativa'), ('cali', 'cali'), ('cucuta', 'cucuta'), ('boyaca', 'boyaca'), ('bogota', 'bogota'), ('apartado', 'apartado'), ('magangue', 'magangue'), ('leticia', 'leticia'), ('fusagasuga', 'fusagasuga'), ('tunja', 'tunja'), ('caucasia', 'caucasia'), ('turbo', 'turbo'), ('girardot', 'girardot'), ('zipaquira', 'zipaquira'), ('barranquilla', 'barranquilla')], max_length=254),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='estado',
            field=models.CharField(choices=[('Disponible', 'disponible'), ('no disponible', 'no disponible'), ('pendiente', 'pendiente')], max_length=254),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='ofrece_transporte',
            field=models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], max_length=254),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='producto',
            field=models.CharField(choices=[('piña', 'piña'), ('manzana', 'manzana'), ('mandarina', 'mandarina'), ('sandia', 'sandia'), ('uva', 'uva'), ('kiwi', 'kiwi'), ('guanabana', 'guanabana'), ('cereza', 'cereza'), ('frambueza', 'frambueza'), ('maracuya', 'maracuya'), ('banano', 'banano'), ('papaya', 'papaya'), ('durazno', 'durazno'), ('melon', 'melon'), ('pera', 'pera'), ('arandanos', 'arandanos'), ('granadilla', 'granadilla'), ('uvas', 'uvas'), ('naranja', 'naranja'), ('ciruela', 'ciruela'), ('limon', 'limon'), ('mora', 'mora'), ('mango', 'mango'), ('pitaya', 'pitaya'), ('fresa', 'fresa')], max_length=254),
        ),
        migrations.AlterField(
            model_name='lacteos',
            name='cantidad',
            field=models.CharField(choices=[('90 kgs', '90 kgs'), ('80 kgs', '80 kgs'), ('100 kgs', '100 kgs'), ('60 kgs', '60 kgs'), ('50 kgs', '50 kgs'), ('70 kgs', '70 kgs')], max_length=100),
        ),
        migrations.AlterField(
            model_name='lacteos',
            name='ciudad',
            field=models.CharField(choices=[('rionegro', 'rionegro'), ('arauca', 'arauca'), ('el carmen de bolivar', 'el carmen de bolivar'), ('medellin', 'medellin'), ('sabanalarga', 'sabanalarga'), ('cartagena', 'cartagena'), ('facatativa', 'facatativa'), ('cali', 'cali'), ('cucuta', 'cucuta'), ('boyaca', 'boyaca'), ('bogota', 'bogota'), ('apartado', 'apartado'), ('magangue', 'magangue'), ('leticia', 'leticia'), ('fusagasuga', 'fusagasuga'), ('tunja', 'tunja'), ('caucasia', 'caucasia'), ('turbo', 'turbo'), ('girardot', 'girardot'), ('zipaquira', 'zipaquira'), ('barranquilla', 'barranquilla')], max_length=50),
        ),
        migrations.AlterField(
            model_name='lacteos',
            name='estado',
            field=models.CharField(choices=[('Disponible', 'disponible'), ('no disponible', 'no disponible'), ('pendiente', 'pendiente')], max_length=50),
        ),
        migrations.AlterField(
            model_name='lacteos',
            name='ofrece_transporte',
            field=models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], max_length=254),
        ),
        migrations.AlterField(
            model_name='leguminosas',
            name='cantidad',
            field=models.CharField(choices=[('90 kgs', '90 kgs'), ('80 kgs', '80 kgs'), ('100 kgs', '100 kgs'), ('60 kgs', '60 kgs'), ('50 kgs', '50 kgs'), ('70 kgs', '70 kgs')], max_length=100),
        ),
        migrations.AlterField(
            model_name='leguminosas',
            name='ciudad',
            field=models.CharField(choices=[('rionegro', 'rionegro'), ('arauca', 'arauca'), ('el carmen de bolivar', 'el carmen de bolivar'), ('medellin', 'medellin'), ('sabanalarga', 'sabanalarga'), ('cartagena', 'cartagena'), ('facatativa', 'facatativa'), ('cali', 'cali'), ('cucuta', 'cucuta'), ('boyaca', 'boyaca'), ('bogota', 'bogota'), ('apartado', 'apartado'), ('magangue', 'magangue'), ('leticia', 'leticia'), ('fusagasuga', 'fusagasuga'), ('tunja', 'tunja'), ('caucasia', 'caucasia'), ('turbo', 'turbo'), ('girardot', 'girardot'), ('zipaquira', 'zipaquira'), ('barranquilla', 'barranquilla')], max_length=50),
        ),
        migrations.AlterField(
            model_name='leguminosas',
            name='estado',
            field=models.CharField(choices=[('Disponible', 'disponible'), ('no disponible', 'no disponible'), ('pendiente', 'pendiente')], max_length=50),
        ),
        migrations.AlterField(
            model_name='leguminosas',
            name='ofrece_transporte',
            field=models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], max_length=254),
        ),
        migrations.AlterField(
            model_name='productor',
            name='ciudad',
            field=models.CharField(choices=[('rionegro', 'rionegro'), ('arauca', 'arauca'), ('el carmen de bolivar', 'el carmen de bolivar'), ('medellin', 'medellin'), ('sabanalarga', 'sabanalarga'), ('cartagena', 'cartagena'), ('facatativa', 'facatativa'), ('cali', 'cali'), ('cucuta', 'cucuta'), ('boyaca', 'boyaca'), ('bogota', 'bogota'), ('apartado', 'apartado'), ('magangue', 'magangue'), ('leticia', 'leticia'), ('fusagasuga', 'fusagasuga'), ('tunja', 'tunja'), ('caucasia', 'caucasia'), ('turbo', 'turbo'), ('girardot', 'girardot'), ('zipaquira', 'zipaquira'), ('barranquilla', 'barranquilla')], max_length=40),
        ),
        migrations.AlterField(
            model_name='productos',
            name='cantidad',
            field=models.CharField(choices=[('90 kgs', '90 kgs'), ('80 kgs', '80 kgs'), ('100 kgs', '100 kgs'), ('60 kgs', '60 kgs'), ('50 kgs', '50 kgs'), ('70 kgs', '70 kgs')], max_length=254),
        ),
        migrations.AlterField(
            model_name='productos',
            name='ciudad',
            field=models.CharField(choices=[('rionegro', 'rionegro'), ('arauca', 'arauca'), ('el carmen de bolivar', 'el carmen de bolivar'), ('medellin', 'medellin'), ('sabanalarga', 'sabanalarga'), ('cartagena', 'cartagena'), ('facatativa', 'facatativa'), ('cali', 'cali'), ('cucuta', 'cucuta'), ('boyaca', 'boyaca'), ('bogota', 'bogota'), ('apartado', 'apartado'), ('magangue', 'magangue'), ('leticia', 'leticia'), ('fusagasuga', 'fusagasuga'), ('tunja', 'tunja'), ('caucasia', 'caucasia'), ('turbo', 'turbo'), ('girardot', 'girardot'), ('zipaquira', 'zipaquira'), ('barranquilla', 'barranquilla')], max_length=254),
        ),
        migrations.AlterField(
            model_name='productos',
            name='estado',
            field=models.CharField(choices=[('Disponible', 'disponible'), ('no disponible', 'no disponible'), ('pendiente', 'pendiente')], max_length=254),
        ),
        migrations.AlterField(
            model_name='productos',
            name='ofrece_transporte',
            field=models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], max_length=254),
        ),
        migrations.AlterField(
            model_name='productos',
            name='producto',
            field=models.CharField(choices=[('piña', 'piña'), ('manzana', 'manzana'), ('mandarina', 'mandarina'), ('sandia', 'sandia'), ('uva', 'uva'), ('kiwi', 'kiwi'), ('guanabana', 'guanabana'), ('cereza', 'cereza'), ('frambueza', 'frambueza'), ('maracuya', 'maracuya'), ('banano', 'banano'), ('papaya', 'papaya'), ('durazno', 'durazno'), ('melon', 'melon'), ('pera', 'pera'), ('arandanos', 'arandanos'), ('granadilla', 'granadilla'), ('uvas', 'uvas'), ('naranja', 'naranja'), ('ciruela', 'ciruela'), ('limon', 'limon'), ('mora', 'mora'), ('mango', 'mango'), ('pitaya', 'pitaya'), ('fresa', 'fresa')], max_length=254),
        ),
        migrations.AlterField(
            model_name='registro',
            name='ciudad',
            field=models.CharField(choices=[('rionegro', 'rionegro'), ('arauca', 'arauca'), ('el carmen de bolivar', 'el carmen de bolivar'), ('medellin', 'medellin'), ('sabanalarga', 'sabanalarga'), ('cartagena', 'cartagena'), ('facatativa', 'facatativa'), ('cali', 'cali'), ('cucuta', 'cucuta'), ('boyaca', 'boyaca'), ('bogota', 'bogota'), ('apartado', 'apartado'), ('magangue', 'magangue'), ('leticia', 'leticia'), ('fusagasuga', 'fusagasuga'), ('tunja', 'tunja'), ('caucasia', 'caucasia'), ('turbo', 'turbo'), ('girardot', 'girardot'), ('zipaquira', 'zipaquira'), ('barranquilla', 'barranquilla')], max_length=40),
        ),
        migrations.AlterField(
            model_name='verduras',
            name='cantidad',
            field=models.CharField(choices=[('90 kgs', '90 kgs'), ('80 kgs', '80 kgs'), ('100 kgs', '100 kgs'), ('60 kgs', '60 kgs'), ('50 kgs', '50 kgs'), ('70 kgs', '70 kgs')], max_length=100),
        ),
        migrations.AlterField(
            model_name='verduras',
            name='ciudad',
            field=models.CharField(choices=[('rionegro', 'rionegro'), ('arauca', 'arauca'), ('el carmen de bolivar', 'el carmen de bolivar'), ('medellin', 'medellin'), ('sabanalarga', 'sabanalarga'), ('cartagena', 'cartagena'), ('facatativa', 'facatativa'), ('cali', 'cali'), ('cucuta', 'cucuta'), ('boyaca', 'boyaca'), ('bogota', 'bogota'), ('apartado', 'apartado'), ('magangue', 'magangue'), ('leticia', 'leticia'), ('fusagasuga', 'fusagasuga'), ('tunja', 'tunja'), ('caucasia', 'caucasia'), ('turbo', 'turbo'), ('girardot', 'girardot'), ('zipaquira', 'zipaquira'), ('barranquilla', 'barranquilla')], max_length=50),
        ),
        migrations.AlterField(
            model_name='verduras',
            name='estado',
            field=models.CharField(choices=[('Disponible', 'disponible'), ('no disponible', 'no disponible'), ('pendiente', 'pendiente')], max_length=50),
        ),
        migrations.AlterField(
            model_name='verduras',
            name='ofrece_transporte',
            field=models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], max_length=254),
        ),
        migrations.AlterField(
            model_name='verduras',
            name='producto',
            field=models.CharField(choices=[('pepino', 'pepino'), ('espinaca', 'espinaca'), ('repollo', 'repollo'), ('tomate', 'tomate'), ('habichuela', 'habichuela'), ('bruselas', 'bruselas'), ('apio', 'apio'), ('coliflor', 'coliflor'), ('lechuga', 'lechuga'), ('acelga', 'acelga'), ('zanahoria', 'zanahoria'), ('champiñon', 'champiñon'), ('pimenton', 'pimenton'), ('arbeja', 'arbeja'), ('rabano', 'rabano'), ('ahuyama', 'ahuyama'), ('cebolla larga', 'cebolla larga'), ('aguacate', 'aguacate'), ('brocoli', 'brocoli'), ('cilantro', 'cilantro'), ('remolacha', 'remolacha'), ('berenjena', 'berenjena'), ('zukini', 'zukini'), ('cebolla cabezona', 'cebolla cabezona')], max_length=100),
        ),
    ]
