# Generated by Django 4.1.3 on 2022-12-11 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_conductor_vehiculo_alter_abarrotes_cantidad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abarrotes',
            name='cantidad',
            field=models.CharField(choices=[('60 kgs', '60 kgs'), ('70 kgs', '70 kgs'), ('80 kgs', '80 kgs'), ('50 kgs', '50 kgs'), ('90 kgs', '90 kgs'), ('100 kgs', '100 kgs')], max_length=100),
        ),
        migrations.AlterField(
            model_name='abarrotes',
            name='ciudad',
            field=models.CharField(choices=[('bogota', 'bogota'), ('cali', 'cali'), ('cucuta', 'cucuta'), ('barranquilla', 'barranquilla'), ('facatativa', 'facatativa'), ('medellin', 'medellin'), ('leticia', 'leticia'), ('sabanalarga', 'sabanalarga'), ('cartagena', 'cartagena'), ('tunja', 'tunja'), ('arauca', 'arauca'), ('el carmen de bolivar', 'el carmen de bolivar'), ('boyaca', 'boyaca'), ('caucasia', 'caucasia'), ('rionegro', 'rionegro'), ('magangue', 'magangue'), ('zipaquira', 'zipaquira'), ('fusagasuga', 'fusagasuga'), ('apartado', 'apartado'), ('girardot', 'girardot'), ('turbo', 'turbo')], max_length=50),
        ),
        migrations.AlterField(
            model_name='abarrotes',
            name='ofrece_transporte',
            field=models.CharField(choices=[('NO', 'NO'), ('SI', 'SI')], max_length=254),
        ),
        migrations.AlterField(
            model_name='carnes',
            name='cantidad',
            field=models.CharField(choices=[('60 kgs', '60 kgs'), ('70 kgs', '70 kgs'), ('80 kgs', '80 kgs'), ('50 kgs', '50 kgs'), ('90 kgs', '90 kgs'), ('100 kgs', '100 kgs')], max_length=100),
        ),
        migrations.AlterField(
            model_name='carnes',
            name='ciudad',
            field=models.CharField(choices=[('bogota', 'bogota'), ('cali', 'cali'), ('cucuta', 'cucuta'), ('barranquilla', 'barranquilla'), ('facatativa', 'facatativa'), ('medellin', 'medellin'), ('leticia', 'leticia'), ('sabanalarga', 'sabanalarga'), ('cartagena', 'cartagena'), ('tunja', 'tunja'), ('arauca', 'arauca'), ('el carmen de bolivar', 'el carmen de bolivar'), ('boyaca', 'boyaca'), ('caucasia', 'caucasia'), ('rionegro', 'rionegro'), ('magangue', 'magangue'), ('zipaquira', 'zipaquira'), ('fusagasuga', 'fusagasuga'), ('apartado', 'apartado'), ('girardot', 'girardot'), ('turbo', 'turbo')], max_length=50),
        ),
        migrations.AlterField(
            model_name='carnes',
            name='ofrece_transporte',
            field=models.CharField(choices=[('NO', 'NO'), ('SI', 'SI')], max_length=254),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='ciudad',
            field=models.CharField(choices=[('bogota', 'bogota'), ('cali', 'cali'), ('cucuta', 'cucuta'), ('barranquilla', 'barranquilla'), ('facatativa', 'facatativa'), ('medellin', 'medellin'), ('leticia', 'leticia'), ('sabanalarga', 'sabanalarga'), ('cartagena', 'cartagena'), ('tunja', 'tunja'), ('arauca', 'arauca'), ('el carmen de bolivar', 'el carmen de bolivar'), ('boyaca', 'boyaca'), ('caucasia', 'caucasia'), ('rionegro', 'rionegro'), ('magangue', 'magangue'), ('zipaquira', 'zipaquira'), ('fusagasuga', 'fusagasuga'), ('apartado', 'apartado'), ('girardot', 'girardot'), ('turbo', 'turbo')], max_length=40),
        ),
        migrations.AlterField(
            model_name='conductor',
            name='ciudad',
            field=models.CharField(choices=[('bogota', 'bogota'), ('cali', 'cali'), ('cucuta', 'cucuta'), ('barranquilla', 'barranquilla'), ('facatativa', 'facatativa'), ('medellin', 'medellin'), ('leticia', 'leticia'), ('sabanalarga', 'sabanalarga'), ('cartagena', 'cartagena'), ('tunja', 'tunja'), ('arauca', 'arauca'), ('el carmen de bolivar', 'el carmen de bolivar'), ('boyaca', 'boyaca'), ('caucasia', 'caucasia'), ('rionegro', 'rionegro'), ('magangue', 'magangue'), ('zipaquira', 'zipaquira'), ('fusagasuga', 'fusagasuga'), ('apartado', 'apartado'), ('girardot', 'girardot'), ('turbo', 'turbo')], max_length=40),
        ),
        migrations.AlterField(
            model_name='frutas',
            name='cantidad',
            field=models.CharField(choices=[('60 kgs', '60 kgs'), ('70 kgs', '70 kgs'), ('80 kgs', '80 kgs'), ('50 kgs', '50 kgs'), ('90 kgs', '90 kgs'), ('100 kgs', '100 kgs')], max_length=100),
        ),
        migrations.AlterField(
            model_name='frutas',
            name='ciudad',
            field=models.CharField(choices=[('bogota', 'bogota'), ('cali', 'cali'), ('cucuta', 'cucuta'), ('barranquilla', 'barranquilla'), ('facatativa', 'facatativa'), ('medellin', 'medellin'), ('leticia', 'leticia'), ('sabanalarga', 'sabanalarga'), ('cartagena', 'cartagena'), ('tunja', 'tunja'), ('arauca', 'arauca'), ('el carmen de bolivar', 'el carmen de bolivar'), ('boyaca', 'boyaca'), ('caucasia', 'caucasia'), ('rionegro', 'rionegro'), ('magangue', 'magangue'), ('zipaquira', 'zipaquira'), ('fusagasuga', 'fusagasuga'), ('apartado', 'apartado'), ('girardot', 'girardot'), ('turbo', 'turbo')], max_length=50),
        ),
        migrations.AlterField(
            model_name='frutas',
            name='ofrece_transporte',
            field=models.CharField(choices=[('NO', 'NO'), ('SI', 'SI')], max_length=254),
        ),
        migrations.AlterField(
            model_name='frutas',
            name='producto',
            field=models.CharField(choices=[('sandia', 'sandia'), ('mora', 'mora'), ('durazno', 'durazno'), ('uvas', 'uvas'), ('uva', 'uva'), ('piña', 'piña'), ('pera', 'pera'), ('papaya', 'papaya'), ('mandarina', 'mandarina'), ('naranja', 'naranja'), ('frambueza', 'frambueza'), ('guanabana', 'guanabana'), ('limon', 'limon'), ('cereza', 'cereza'), ('melon', 'melon'), ('arandanos', 'arandanos'), ('ciruela', 'ciruela'), ('banano', 'banano'), ('pitaya', 'pitaya'), ('manzana', 'manzana'), ('kiwi', 'kiwi'), ('granadilla', 'granadilla'), ('fresa', 'fresa'), ('mango', 'mango'), ('maracuya', 'maracuya')], max_length=100),
        ),
        migrations.AlterField(
            model_name='granos',
            name='cantidad',
            field=models.CharField(choices=[('60 kgs', '60 kgs'), ('70 kgs', '70 kgs'), ('80 kgs', '80 kgs'), ('50 kgs', '50 kgs'), ('90 kgs', '90 kgs'), ('100 kgs', '100 kgs')], max_length=100),
        ),
        migrations.AlterField(
            model_name='granos',
            name='ciudad',
            field=models.CharField(choices=[('bogota', 'bogota'), ('cali', 'cali'), ('cucuta', 'cucuta'), ('barranquilla', 'barranquilla'), ('facatativa', 'facatativa'), ('medellin', 'medellin'), ('leticia', 'leticia'), ('sabanalarga', 'sabanalarga'), ('cartagena', 'cartagena'), ('tunja', 'tunja'), ('arauca', 'arauca'), ('el carmen de bolivar', 'el carmen de bolivar'), ('boyaca', 'boyaca'), ('caucasia', 'caucasia'), ('rionegro', 'rionegro'), ('magangue', 'magangue'), ('zipaquira', 'zipaquira'), ('fusagasuga', 'fusagasuga'), ('apartado', 'apartado'), ('girardot', 'girardot'), ('turbo', 'turbo')], max_length=50),
        ),
        migrations.AlterField(
            model_name='granos',
            name='ofrece_transporte',
            field=models.CharField(choices=[('NO', 'NO'), ('SI', 'SI')], max_length=254),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='cantidad',
            field=models.CharField(choices=[('60 kgs', '60 kgs'), ('70 kgs', '70 kgs'), ('80 kgs', '80 kgs'), ('50 kgs', '50 kgs'), ('90 kgs', '90 kgs'), ('100 kgs', '100 kgs')], max_length=254),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='ciudad',
            field=models.CharField(choices=[('bogota', 'bogota'), ('cali', 'cali'), ('cucuta', 'cucuta'), ('barranquilla', 'barranquilla'), ('facatativa', 'facatativa'), ('medellin', 'medellin'), ('leticia', 'leticia'), ('sabanalarga', 'sabanalarga'), ('cartagena', 'cartagena'), ('tunja', 'tunja'), ('arauca', 'arauca'), ('el carmen de bolivar', 'el carmen de bolivar'), ('boyaca', 'boyaca'), ('caucasia', 'caucasia'), ('rionegro', 'rionegro'), ('magangue', 'magangue'), ('zipaquira', 'zipaquira'), ('fusagasuga', 'fusagasuga'), ('apartado', 'apartado'), ('girardot', 'girardot'), ('turbo', 'turbo')], max_length=254),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='ofrece_transporte',
            field=models.CharField(choices=[('NO', 'NO'), ('SI', 'SI')], max_length=254),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='producto',
            field=models.CharField(choices=[('sandia', 'sandia'), ('mora', 'mora'), ('durazno', 'durazno'), ('uvas', 'uvas'), ('uva', 'uva'), ('piña', 'piña'), ('pera', 'pera'), ('papaya', 'papaya'), ('mandarina', 'mandarina'), ('naranja', 'naranja'), ('frambueza', 'frambueza'), ('guanabana', 'guanabana'), ('limon', 'limon'), ('cereza', 'cereza'), ('melon', 'melon'), ('arandanos', 'arandanos'), ('ciruela', 'ciruela'), ('banano', 'banano'), ('pitaya', 'pitaya'), ('manzana', 'manzana'), ('kiwi', 'kiwi'), ('granadilla', 'granadilla'), ('fresa', 'fresa'), ('mango', 'mango'), ('maracuya', 'maracuya')], max_length=254),
        ),
        migrations.AlterField(
            model_name='lacteos',
            name='cantidad',
            field=models.CharField(choices=[('60 kgs', '60 kgs'), ('70 kgs', '70 kgs'), ('80 kgs', '80 kgs'), ('50 kgs', '50 kgs'), ('90 kgs', '90 kgs'), ('100 kgs', '100 kgs')], max_length=100),
        ),
        migrations.AlterField(
            model_name='lacteos',
            name='ciudad',
            field=models.CharField(choices=[('bogota', 'bogota'), ('cali', 'cali'), ('cucuta', 'cucuta'), ('barranquilla', 'barranquilla'), ('facatativa', 'facatativa'), ('medellin', 'medellin'), ('leticia', 'leticia'), ('sabanalarga', 'sabanalarga'), ('cartagena', 'cartagena'), ('tunja', 'tunja'), ('arauca', 'arauca'), ('el carmen de bolivar', 'el carmen de bolivar'), ('boyaca', 'boyaca'), ('caucasia', 'caucasia'), ('rionegro', 'rionegro'), ('magangue', 'magangue'), ('zipaquira', 'zipaquira'), ('fusagasuga', 'fusagasuga'), ('apartado', 'apartado'), ('girardot', 'girardot'), ('turbo', 'turbo')], max_length=50),
        ),
        migrations.AlterField(
            model_name='lacteos',
            name='ofrece_transporte',
            field=models.CharField(choices=[('NO', 'NO'), ('SI', 'SI')], max_length=254),
        ),
        migrations.AlterField(
            model_name='leguminosas',
            name='cantidad',
            field=models.CharField(choices=[('60 kgs', '60 kgs'), ('70 kgs', '70 kgs'), ('80 kgs', '80 kgs'), ('50 kgs', '50 kgs'), ('90 kgs', '90 kgs'), ('100 kgs', '100 kgs')], max_length=100),
        ),
        migrations.AlterField(
            model_name='leguminosas',
            name='ciudad',
            field=models.CharField(choices=[('bogota', 'bogota'), ('cali', 'cali'), ('cucuta', 'cucuta'), ('barranquilla', 'barranquilla'), ('facatativa', 'facatativa'), ('medellin', 'medellin'), ('leticia', 'leticia'), ('sabanalarga', 'sabanalarga'), ('cartagena', 'cartagena'), ('tunja', 'tunja'), ('arauca', 'arauca'), ('el carmen de bolivar', 'el carmen de bolivar'), ('boyaca', 'boyaca'), ('caucasia', 'caucasia'), ('rionegro', 'rionegro'), ('magangue', 'magangue'), ('zipaquira', 'zipaquira'), ('fusagasuga', 'fusagasuga'), ('apartado', 'apartado'), ('girardot', 'girardot'), ('turbo', 'turbo')], max_length=50),
        ),
        migrations.AlterField(
            model_name='leguminosas',
            name='ofrece_transporte',
            field=models.CharField(choices=[('NO', 'NO'), ('SI', 'SI')], max_length=254),
        ),
        migrations.AlterField(
            model_name='productor',
            name='ciudad',
            field=models.CharField(choices=[('bogota', 'bogota'), ('cali', 'cali'), ('cucuta', 'cucuta'), ('barranquilla', 'barranquilla'), ('facatativa', 'facatativa'), ('medellin', 'medellin'), ('leticia', 'leticia'), ('sabanalarga', 'sabanalarga'), ('cartagena', 'cartagena'), ('tunja', 'tunja'), ('arauca', 'arauca'), ('el carmen de bolivar', 'el carmen de bolivar'), ('boyaca', 'boyaca'), ('caucasia', 'caucasia'), ('rionegro', 'rionegro'), ('magangue', 'magangue'), ('zipaquira', 'zipaquira'), ('fusagasuga', 'fusagasuga'), ('apartado', 'apartado'), ('girardot', 'girardot'), ('turbo', 'turbo')], max_length=40),
        ),
        migrations.AlterField(
            model_name='productos',
            name='cantidad',
            field=models.CharField(choices=[('60 kgs', '60 kgs'), ('70 kgs', '70 kgs'), ('80 kgs', '80 kgs'), ('50 kgs', '50 kgs'), ('90 kgs', '90 kgs'), ('100 kgs', '100 kgs')], max_length=254),
        ),
        migrations.AlterField(
            model_name='productos',
            name='ciudad',
            field=models.CharField(choices=[('bogota', 'bogota'), ('cali', 'cali'), ('cucuta', 'cucuta'), ('barranquilla', 'barranquilla'), ('facatativa', 'facatativa'), ('medellin', 'medellin'), ('leticia', 'leticia'), ('sabanalarga', 'sabanalarga'), ('cartagena', 'cartagena'), ('tunja', 'tunja'), ('arauca', 'arauca'), ('el carmen de bolivar', 'el carmen de bolivar'), ('boyaca', 'boyaca'), ('caucasia', 'caucasia'), ('rionegro', 'rionegro'), ('magangue', 'magangue'), ('zipaquira', 'zipaquira'), ('fusagasuga', 'fusagasuga'), ('apartado', 'apartado'), ('girardot', 'girardot'), ('turbo', 'turbo')], max_length=254),
        ),
        migrations.AlterField(
            model_name='productos',
            name='ofrece_transporte',
            field=models.CharField(choices=[('NO', 'NO'), ('SI', 'SI')], max_length=254),
        ),
        migrations.AlterField(
            model_name='productos',
            name='producto',
            field=models.CharField(choices=[('sandia', 'sandia'), ('mora', 'mora'), ('durazno', 'durazno'), ('uvas', 'uvas'), ('uva', 'uva'), ('piña', 'piña'), ('pera', 'pera'), ('papaya', 'papaya'), ('mandarina', 'mandarina'), ('naranja', 'naranja'), ('frambueza', 'frambueza'), ('guanabana', 'guanabana'), ('limon', 'limon'), ('cereza', 'cereza'), ('melon', 'melon'), ('arandanos', 'arandanos'), ('ciruela', 'ciruela'), ('banano', 'banano'), ('pitaya', 'pitaya'), ('manzana', 'manzana'), ('kiwi', 'kiwi'), ('granadilla', 'granadilla'), ('fresa', 'fresa'), ('mango', 'mango'), ('maracuya', 'maracuya')], max_length=254),
        ),
        migrations.AlterField(
            model_name='registro',
            name='ciudad',
            field=models.CharField(choices=[('bogota', 'bogota'), ('cali', 'cali'), ('cucuta', 'cucuta'), ('barranquilla', 'barranquilla'), ('facatativa', 'facatativa'), ('medellin', 'medellin'), ('leticia', 'leticia'), ('sabanalarga', 'sabanalarga'), ('cartagena', 'cartagena'), ('tunja', 'tunja'), ('arauca', 'arauca'), ('el carmen de bolivar', 'el carmen de bolivar'), ('boyaca', 'boyaca'), ('caucasia', 'caucasia'), ('rionegro', 'rionegro'), ('magangue', 'magangue'), ('zipaquira', 'zipaquira'), ('fusagasuga', 'fusagasuga'), ('apartado', 'apartado'), ('girardot', 'girardot'), ('turbo', 'turbo')], max_length=40),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='capacidad',
            field=models.CharField(choices=[('4_TONELADA', '4_TONELADA'), ('21_TONELADA', '21_TONELADA'), ('24_TONELADA', '24_TONELADA'), ('27_TONOLEDA', '27_TONOLEDA'), ('30_TONOLEDA', '30_TONOLEDA'), ('7_TONELADA', '7_TONELADA'), ('500_KGS', '500_KGS'), ('12_TONELADA', '12_TONELADA'), ('1_TONELADA', '1_TONELADA'), ('6_TONOLEDA', '6_TONOLEDA'), ('3_TONOLEDA', '3_TONOLEDA'), ('10_TONELADA', '10_TONELADA'), ('15_TONELADA', '15_TONELADA'), ('9_TONELADA', '9_TONELADA'), ('32_TONOLEDA', '32_TONOLEDA'), ('18_TONOLEDA', '18_TONOLEDA'), ('13_TONOLEDA', '13_TONOLEDA'), ('11_TONOLEDA', '11_TONOLEDA'), ('5_TONELADA', '5_TONELADA'), ('2_TONELADA', '2_TONELADA'), ('8_TONOLEDA', '8_TONOLEDA')], max_length=100),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='color',
            field=models.CharField(choices=[('blanco', 'blanco'), ('azul', 'azul'), ('amarillo', 'amarillo'), ('dorado', 'dorado'), ('rojo', 'rojo'), ('rosado', 'rosado'), ('gris', 'gris'), ('cafe', 'cafe'), ('morado', 'morado'), ('perlado', 'perlado'), ('negro', 'negro'), ('naranja', 'naranja')], max_length=100),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='marca',
            field=models.CharField(choices=[('HIUNDAY', 'HIUNDAY'), ('TOYOTA', 'TOYOTA'), ('NISSAN', 'NISSAN'), ('FORD', 'FORD'), ('CHEVROLET', 'CHEVROLET'), ('MAZDA', 'MAZDA'), ('KIA', 'KIA')], max_length=254),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='tipo_carroceria',
            field=models.CharField(choices=[('furgon', 'furgon'), ('platon', 'platon'), ('estacas', 'estacas'), ('termoquin', 'termoquin')], max_length=100),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='tipo_vehiculo',
            field=models.CharField(choices=[('Cuatro manos', 'Cuatro manos'), ('Luv', 'Luv'), ('Turbo', 'Turbo'), ('Doble troque', 'Doble troque'), ('Camion grande', 'Camion grande'), ('Minimula', 'Minimula'), ('Camion sencillo', 'Camion sencillo'), ('Tractomula 2 troques', 'Tractomula 2 troques'), ('Tractomula 3 troques', 'Tractomula 3 troques')], max_length=100),
        ),
        migrations.AlterField(
            model_name='verduras',
            name='cantidad',
            field=models.CharField(choices=[('60 kgs', '60 kgs'), ('70 kgs', '70 kgs'), ('80 kgs', '80 kgs'), ('50 kgs', '50 kgs'), ('90 kgs', '90 kgs'), ('100 kgs', '100 kgs')], max_length=100),
        ),
        migrations.AlterField(
            model_name='verduras',
            name='ciudad',
            field=models.CharField(choices=[('bogota', 'bogota'), ('cali', 'cali'), ('cucuta', 'cucuta'), ('barranquilla', 'barranquilla'), ('facatativa', 'facatativa'), ('medellin', 'medellin'), ('leticia', 'leticia'), ('sabanalarga', 'sabanalarga'), ('cartagena', 'cartagena'), ('tunja', 'tunja'), ('arauca', 'arauca'), ('el carmen de bolivar', 'el carmen de bolivar'), ('boyaca', 'boyaca'), ('caucasia', 'caucasia'), ('rionegro', 'rionegro'), ('magangue', 'magangue'), ('zipaquira', 'zipaquira'), ('fusagasuga', 'fusagasuga'), ('apartado', 'apartado'), ('girardot', 'girardot'), ('turbo', 'turbo')], max_length=50),
        ),
        migrations.AlterField(
            model_name='verduras',
            name='ofrece_transporte',
            field=models.CharField(choices=[('NO', 'NO'), ('SI', 'SI')], max_length=254),
        ),
        migrations.AlterField(
            model_name='verduras',
            name='producto',
            field=models.CharField(choices=[('rabano', 'rabano'), ('berenjena', 'berenjena'), ('lechuga', 'lechuga'), ('pepino', 'pepino'), ('zanahoria', 'zanahoria'), ('zukini', 'zukini'), ('bruselas', 'bruselas'), ('repollo', 'repollo'), ('espinaca', 'espinaca'), ('cilantro', 'cilantro'), ('ahuyama', 'ahuyama'), ('tomate', 'tomate'), ('pimenton', 'pimenton'), ('coliflor', 'coliflor'), ('brocoli', 'brocoli'), ('habichuela', 'habichuela'), ('remolacha', 'remolacha'), ('aguacate', 'aguacate'), ('cebolla larga', 'cebolla larga'), ('cebolla cabezona', 'cebolla cabezona'), ('champiñon', 'champiñon'), ('apio', 'apio'), ('acelga', 'acelga'), ('arbeja', 'arbeja')], max_length=100),
        ),
    ]
