# Generated by Django 4.1.3 on 2022-11-19 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_login_alter_driver_vehicle_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='distribuidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('identification_card', models.CharField(max_length=10)),
                ('direction', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=10)),
                ('cell_phone', models.CharField(max_length=11)),
                ('email', models.CharField(max_length=254)),
                ('city', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=254)),
            ],
            options={
                'db_table': 'distribuidor',
            },
        ),
        migrations.AlterField(
            model_name='driver',
            name='vehicle_type',
            field=models.CharField(choices=[('Pickup', 'Pickup'), ('Doble troque', 'Doble troque'), ('Tractomula 2 troques', 'Tractomula 2 troques'), ('Cuatro manos', 'Cuatro manos'), ('Camion sencillo', 'Camion'), ('Luv', 'Luv'), ('Turbo', 'Turbo'), ('Minimula', 'Minimula'), ('Tractomula 3 troques', 'Tractomula 3 troques')], max_length=254, null=True),
        ),
    ]
