# Generated by Django 4.1.3 on 2022-11-22 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_distribuidor_alter_driver_vehicle_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'registro',
            },
        ),
        migrations.AlterField(
            model_name='driver',
            name='vehicle_type',
            field=models.CharField(choices=[('Camion sencillo', 'Camion'), ('Tractomula 3 troques', 'Tractomula 3 troques'), ('Turbo', 'Turbo'), ('Cuatro manos', 'Cuatro manos'), ('Luv', 'Luv'), ('Doble troque', 'Doble troque'), ('Pickup', 'Pickup'), ('Tractomula 2 troques', 'Tractomula 2 troques'), ('Minimula', 'Minimula')], max_length=254, null=True),
        ),
    ]
