# Generated by Django 4.1.3 on 2022-12-12 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_abarrotes_cantidad_alter_abarrotes_ciudad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abarrotes',
            name='cantidad',
            field=models.CharField(choices=[('100 kgs', '100 kgs'), ('80 kgs', '80 kgs'), ('60 kgs', '60 kgs'), ('70 kgs', '70 kgs'), ('50 kgs', '50 kgs'), ('90 kgs', '90 kgs')], max_length=100),
        ),
        migrations.AlterField(
            model_name='abarrotes',
            name='ciudad',
            field=models.CharField(choices=[('cartagena', 'cartagena'), ('zipaquira', 'zipaquira'), ('bogota', 'bogota'), ('cali', 'cali'), ('caucasia', 'caucasia'), ('el carmen de bolivar', 'el carmen de bolivar'), ('facatativa', 'facatativa'), ('boyaca', 'boyaca'), ('tunja', 'tunja'), ('barranquilla', 'barranquilla'), ('turbo', 'turbo'), ('leticia', 'leticia'), ('medellin', 'medellin'), ('rionegro', 'rionegro'), ('sabanalarga', 'sabanalarga'), ('girardot', 'girardot'), ('fusagasuga', 'fusagasuga'), ('cucuta', 'cucuta'), ('apartado', 'apartado'), ('arauca', 'arauca'), ('magangue', 'magangue')], max_length=50),
        ),
        migrations.AlterField(
            model_name='carnes',
            name='cantidad',
            field=models.CharField(choices=[('100 kgs', '100 kgs'), ('80 kgs', '80 kgs'), ('60 kgs', '60 kgs'), ('70 kgs', '70 kgs'), ('50 kgs', '50 kgs'), ('90 kgs', '90 kgs')], max_length=100),
        ),
        migrations.AlterField(
            model_name='carnes',
            name='ciudad',
            field=models.CharField(choices=[('cartagena', 'cartagena'), ('zipaquira', 'zipaquira'), ('bogota', 'bogota'), ('cali', 'cali'), ('caucasia', 'caucasia'), ('el carmen de bolivar', 'el carmen de bolivar'), ('facatativa', 'facatativa'), ('boyaca', 'boyaca'), ('tunja', 'tunja'), ('barranquilla', 'barranquilla'), ('turbo', 'turbo'), ('leticia', 'leticia'), ('medellin', 'medellin'), ('rionegro', 'rionegro'), ('sabanalarga', 'sabanalarga'), ('girardot', 'girardot'), ('fusagasuga', 'fusagasuga'), ('cucuta', 'cucuta'), ('apartado', 'apartado'), ('arauca', 'arauca'), ('magangue', 'magangue')], max_length=50),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='ciudad',
            field=models.CharField(choices=[('cartagena', 'cartagena'), ('zipaquira', 'zipaquira'), ('bogota', 'bogota'), ('cali', 'cali'), ('caucasia', 'caucasia'), ('el carmen de bolivar', 'el carmen de bolivar'), ('facatativa', 'facatativa'), ('boyaca', 'boyaca'), ('tunja', 'tunja'), ('barranquilla', 'barranquilla'), ('turbo', 'turbo'), ('leticia', 'leticia'), ('medellin', 'medellin'), ('rionegro', 'rionegro'), ('sabanalarga', 'sabanalarga'), ('girardot', 'girardot'), ('fusagasuga', 'fusagasuga'), ('cucuta', 'cucuta'), ('apartado', 'apartado'), ('arauca', 'arauca'), ('magangue', 'magangue')], max_length=40),
        ),
        migrations.AlterField(
            model_name='conductor',
            name='ciudad',
            field=models.CharField(choices=[('cartagena', 'cartagena'), ('zipaquira', 'zipaquira'), ('bogota', 'bogota'), ('cali', 'cali'), ('caucasia', 'caucasia'), ('el carmen de bolivar', 'el carmen de bolivar'), ('facatativa', 'facatativa'), ('boyaca', 'boyaca'), ('tunja', 'tunja'), ('barranquilla', 'barranquilla'), ('turbo', 'turbo'), ('leticia', 'leticia'), ('medellin', 'medellin'), ('rionegro', 'rionegro'), ('sabanalarga', 'sabanalarga'), ('girardot', 'girardot'), ('fusagasuga', 'fusagasuga'), ('cucuta', 'cucuta'), ('apartado', 'apartado'), ('arauca', 'arauca'), ('magangue', 'magangue')], max_length=40),
        ),
        migrations.AlterField(
            model_name='frutas',
            name='cantidad',
            field=models.CharField(choices=[('100 kgs', '100 kgs'), ('80 kgs', '80 kgs'), ('60 kgs', '60 kgs'), ('70 kgs', '70 kgs'), ('50 kgs', '50 kgs'), ('90 kgs', '90 kgs')], max_length=100),
        ),
        migrations.AlterField(
            model_name='frutas',
            name='ciudad',
            field=models.CharField(choices=[('cartagena', 'cartagena'), ('zipaquira', 'zipaquira'), ('bogota', 'bogota'), ('cali', 'cali'), ('caucasia', 'caucasia'), ('el carmen de bolivar', 'el carmen de bolivar'), ('facatativa', 'facatativa'), ('boyaca', 'boyaca'), ('tunja', 'tunja'), ('barranquilla', 'barranquilla'), ('turbo', 'turbo'), ('leticia', 'leticia'), ('medellin', 'medellin'), ('rionegro', 'rionegro'), ('sabanalarga', 'sabanalarga'), ('girardot', 'girardot'), ('fusagasuga', 'fusagasuga'), ('cucuta', 'cucuta'), ('apartado', 'apartado'), ('arauca', 'arauca'), ('magangue', 'magangue')], max_length=50),
        ),
        migrations.AlterField(
            model_name='frutas',
            name='producto',
            field=models.CharField(choices=[('mora', 'mora'), ('durazno', 'durazno'), ('maracuya', 'maracuya'), ('limon', 'limon'), ('banano', 'banano'), ('mandarina', 'mandarina'), ('fresa', 'fresa'), ('naranja', 'naranja'), ('uva', 'uva'), ('melon', 'melon'), ('granadilla', 'granadilla'), ('frambueza', 'frambueza'), ('kiwi', 'kiwi'), ('cereza', 'cereza'), ('mango', 'mango'), ('arandanos', 'arandanos'), ('pitaya', 'pitaya'), ('ciruela', 'ciruela'), ('papaya', 'papaya'), ('pera', 'pera'), ('uvas', 'uvas'), ('manzana', 'manzana'), ('guanabana', 'guanabana'), ('sandia', 'sandia'), ('piña', 'piña')], max_length=100),
        ),
        migrations.AlterField(
            model_name='granos',
            name='cantidad',
            field=models.CharField(choices=[('100 kgs', '100 kgs'), ('80 kgs', '80 kgs'), ('60 kgs', '60 kgs'), ('70 kgs', '70 kgs'), ('50 kgs', '50 kgs'), ('90 kgs', '90 kgs')], max_length=100),
        ),
        migrations.AlterField(
            model_name='granos',
            name='ciudad',
            field=models.CharField(choices=[('cartagena', 'cartagena'), ('zipaquira', 'zipaquira'), ('bogota', 'bogota'), ('cali', 'cali'), ('caucasia', 'caucasia'), ('el carmen de bolivar', 'el carmen de bolivar'), ('facatativa', 'facatativa'), ('boyaca', 'boyaca'), ('tunja', 'tunja'), ('barranquilla', 'barranquilla'), ('turbo', 'turbo'), ('leticia', 'leticia'), ('medellin', 'medellin'), ('rionegro', 'rionegro'), ('sabanalarga', 'sabanalarga'), ('girardot', 'girardot'), ('fusagasuga', 'fusagasuga'), ('cucuta', 'cucuta'), ('apartado', 'apartado'), ('arauca', 'arauca'), ('magangue', 'magangue')], max_length=50),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='cantidad',
            field=models.CharField(choices=[('100 kgs', '100 kgs'), ('80 kgs', '80 kgs'), ('60 kgs', '60 kgs'), ('70 kgs', '70 kgs'), ('50 kgs', '50 kgs'), ('90 kgs', '90 kgs')], max_length=254),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='ciudad',
            field=models.CharField(choices=[('cartagena', 'cartagena'), ('zipaquira', 'zipaquira'), ('bogota', 'bogota'), ('cali', 'cali'), ('caucasia', 'caucasia'), ('el carmen de bolivar', 'el carmen de bolivar'), ('facatativa', 'facatativa'), ('boyaca', 'boyaca'), ('tunja', 'tunja'), ('barranquilla', 'barranquilla'), ('turbo', 'turbo'), ('leticia', 'leticia'), ('medellin', 'medellin'), ('rionegro', 'rionegro'), ('sabanalarga', 'sabanalarga'), ('girardot', 'girardot'), ('fusagasuga', 'fusagasuga'), ('cucuta', 'cucuta'), ('apartado', 'apartado'), ('arauca', 'arauca'), ('magangue', 'magangue')], max_length=254),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='producto',
            field=models.CharField(choices=[('mora', 'mora'), ('durazno', 'durazno'), ('maracuya', 'maracuya'), ('limon', 'limon'), ('banano', 'banano'), ('mandarina', 'mandarina'), ('fresa', 'fresa'), ('naranja', 'naranja'), ('uva', 'uva'), ('melon', 'melon'), ('granadilla', 'granadilla'), ('frambueza', 'frambueza'), ('kiwi', 'kiwi'), ('cereza', 'cereza'), ('mango', 'mango'), ('arandanos', 'arandanos'), ('pitaya', 'pitaya'), ('ciruela', 'ciruela'), ('papaya', 'papaya'), ('pera', 'pera'), ('uvas', 'uvas'), ('manzana', 'manzana'), ('guanabana', 'guanabana'), ('sandia', 'sandia'), ('piña', 'piña')], max_length=254),
        ),
        migrations.AlterField(
            model_name='lacteos',
            name='cantidad',
            field=models.CharField(choices=[('100 kgs', '100 kgs'), ('80 kgs', '80 kgs'), ('60 kgs', '60 kgs'), ('70 kgs', '70 kgs'), ('50 kgs', '50 kgs'), ('90 kgs', '90 kgs')], max_length=100),
        ),
        migrations.AlterField(
            model_name='lacteos',
            name='ciudad',
            field=models.CharField(choices=[('cartagena', 'cartagena'), ('zipaquira', 'zipaquira'), ('bogota', 'bogota'), ('cali', 'cali'), ('caucasia', 'caucasia'), ('el carmen de bolivar', 'el carmen de bolivar'), ('facatativa', 'facatativa'), ('boyaca', 'boyaca'), ('tunja', 'tunja'), ('barranquilla', 'barranquilla'), ('turbo', 'turbo'), ('leticia', 'leticia'), ('medellin', 'medellin'), ('rionegro', 'rionegro'), ('sabanalarga', 'sabanalarga'), ('girardot', 'girardot'), ('fusagasuga', 'fusagasuga'), ('cucuta', 'cucuta'), ('apartado', 'apartado'), ('arauca', 'arauca'), ('magangue', 'magangue')], max_length=50),
        ),
        migrations.AlterField(
            model_name='leguminosas',
            name='cantidad',
            field=models.CharField(choices=[('100 kgs', '100 kgs'), ('80 kgs', '80 kgs'), ('60 kgs', '60 kgs'), ('70 kgs', '70 kgs'), ('50 kgs', '50 kgs'), ('90 kgs', '90 kgs')], max_length=100),
        ),
        migrations.AlterField(
            model_name='leguminosas',
            name='ciudad',
            field=models.CharField(choices=[('cartagena', 'cartagena'), ('zipaquira', 'zipaquira'), ('bogota', 'bogota'), ('cali', 'cali'), ('caucasia', 'caucasia'), ('el carmen de bolivar', 'el carmen de bolivar'), ('facatativa', 'facatativa'), ('boyaca', 'boyaca'), ('tunja', 'tunja'), ('barranquilla', 'barranquilla'), ('turbo', 'turbo'), ('leticia', 'leticia'), ('medellin', 'medellin'), ('rionegro', 'rionegro'), ('sabanalarga', 'sabanalarga'), ('girardot', 'girardot'), ('fusagasuga', 'fusagasuga'), ('cucuta', 'cucuta'), ('apartado', 'apartado'), ('arauca', 'arauca'), ('magangue', 'magangue')], max_length=50),
        ),
        migrations.AlterField(
            model_name='productor',
            name='ciudad',
            field=models.CharField(choices=[('cartagena', 'cartagena'), ('zipaquira', 'zipaquira'), ('bogota', 'bogota'), ('cali', 'cali'), ('caucasia', 'caucasia'), ('el carmen de bolivar', 'el carmen de bolivar'), ('facatativa', 'facatativa'), ('boyaca', 'boyaca'), ('tunja', 'tunja'), ('barranquilla', 'barranquilla'), ('turbo', 'turbo'), ('leticia', 'leticia'), ('medellin', 'medellin'), ('rionegro', 'rionegro'), ('sabanalarga', 'sabanalarga'), ('girardot', 'girardot'), ('fusagasuga', 'fusagasuga'), ('cucuta', 'cucuta'), ('apartado', 'apartado'), ('arauca', 'arauca'), ('magangue', 'magangue')], max_length=40),
        ),
        migrations.AlterField(
            model_name='productos',
            name='cantidad',
            field=models.CharField(choices=[('100 kgs', '100 kgs'), ('80 kgs', '80 kgs'), ('60 kgs', '60 kgs'), ('70 kgs', '70 kgs'), ('50 kgs', '50 kgs'), ('90 kgs', '90 kgs')], max_length=254),
        ),
        migrations.AlterField(
            model_name='productos',
            name='ciudad',
            field=models.CharField(choices=[('cartagena', 'cartagena'), ('zipaquira', 'zipaquira'), ('bogota', 'bogota'), ('cali', 'cali'), ('caucasia', 'caucasia'), ('el carmen de bolivar', 'el carmen de bolivar'), ('facatativa', 'facatativa'), ('boyaca', 'boyaca'), ('tunja', 'tunja'), ('barranquilla', 'barranquilla'), ('turbo', 'turbo'), ('leticia', 'leticia'), ('medellin', 'medellin'), ('rionegro', 'rionegro'), ('sabanalarga', 'sabanalarga'), ('girardot', 'girardot'), ('fusagasuga', 'fusagasuga'), ('cucuta', 'cucuta'), ('apartado', 'apartado'), ('arauca', 'arauca'), ('magangue', 'magangue')], max_length=254),
        ),
        migrations.AlterField(
            model_name='productos',
            name='producto',
            field=models.CharField(choices=[('mora', 'mora'), ('durazno', 'durazno'), ('maracuya', 'maracuya'), ('limon', 'limon'), ('banano', 'banano'), ('mandarina', 'mandarina'), ('fresa', 'fresa'), ('naranja', 'naranja'), ('uva', 'uva'), ('melon', 'melon'), ('granadilla', 'granadilla'), ('frambueza', 'frambueza'), ('kiwi', 'kiwi'), ('cereza', 'cereza'), ('mango', 'mango'), ('arandanos', 'arandanos'), ('pitaya', 'pitaya'), ('ciruela', 'ciruela'), ('papaya', 'papaya'), ('pera', 'pera'), ('uvas', 'uvas'), ('manzana', 'manzana'), ('guanabana', 'guanabana'), ('sandia', 'sandia'), ('piña', 'piña')], max_length=254),
        ),
        migrations.AlterField(
            model_name='registro',
            name='ciudad',
            field=models.CharField(choices=[('cartagena', 'cartagena'), ('zipaquira', 'zipaquira'), ('bogota', 'bogota'), ('cali', 'cali'), ('caucasia', 'caucasia'), ('el carmen de bolivar', 'el carmen de bolivar'), ('facatativa', 'facatativa'), ('boyaca', 'boyaca'), ('tunja', 'tunja'), ('barranquilla', 'barranquilla'), ('turbo', 'turbo'), ('leticia', 'leticia'), ('medellin', 'medellin'), ('rionegro', 'rionegro'), ('sabanalarga', 'sabanalarga'), ('girardot', 'girardot'), ('fusagasuga', 'fusagasuga'), ('cucuta', 'cucuta'), ('apartado', 'apartado'), ('arauca', 'arauca'), ('magangue', 'magangue')], max_length=40),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='capacidad',
            field=models.CharField(choices=[('5_TONELADA', '5_TONELADA'), ('4_TONELADA', '4_TONELADA'), ('2_TONELADA', '2_TONELADA'), ('24_TONELADA', '24_TONELADA'), ('9_TONELADA', '9_TONELADA'), ('12_TONELADA', '12_TONELADA'), ('8_TONOLEDA', '8_TONOLEDA'), ('27_TONOLEDA', '27_TONOLEDA'), ('3_TONOLEDA', '3_TONOLEDA'), ('13_TONOLEDA', '13_TONOLEDA'), ('1_TONELADA', '1_TONELADA'), ('6_TONOLEDA', '6_TONOLEDA'), ('500_KGS', '500_KGS'), ('10_TONELADA', '10_TONELADA'), ('15_TONELADA', '15_TONELADA'), ('11_TONOLEDA', '11_TONOLEDA'), ('18_TONOLEDA', '18_TONOLEDA'), ('32_TONOLEDA', '32_TONOLEDA'), ('30_TONOLEDA', '30_TONOLEDA'), ('7_TONELADA', '7_TONELADA'), ('21_TONELADA', '21_TONELADA')], max_length=100),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='color',
            field=models.CharField(choices=[('amarillo', 'amarillo'), ('morado', 'morado'), ('rosado', 'rosado'), ('azul', 'azul'), ('dorado', 'dorado'), ('gris', 'gris'), ('cafe', 'cafe'), ('naranja', 'naranja'), ('rojo', 'rojo'), ('perlado', 'perlado'), ('blanco', 'blanco'), ('negro', 'negro')], max_length=100),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='marca',
            field=models.CharField(choices=[('FORD', 'FORD'), ('HIUNDAY', 'HIUNDAY'), ('KIA', 'KIA'), ('CHEVROLET', 'CHEVROLET'), ('NISSAN', 'NISSAN'), ('MAZDA', 'MAZDA'), ('TOYOTA', 'TOYOTA')], max_length=254),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='tipo_carroceria',
            field=models.CharField(choices=[('termoquin', 'termoquin'), ('platon', 'platon'), ('estacas', 'estacas'), ('furgon', 'furgon')], max_length=100),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='tipo_vehiculo',
            field=models.CharField(choices=[('Turbo', 'Turbo'), ('Tractomula 3 troques', 'Tractomula 3 troques'), ('Doble troque', 'Doble troque'), ('Tractomula 2 troques', 'Tractomula 2 troques'), ('Cuatro manos', 'Cuatro manos'), ('Minimula', 'Minimula'), ('Camion grande', 'Camion grande'), ('Camion sencillo', 'Camion sencillo'), ('Luv', 'Luv')], max_length=100),
        ),
        migrations.AlterField(
            model_name='verduras',
            name='cantidad',
            field=models.CharField(choices=[('100 kgs', '100 kgs'), ('80 kgs', '80 kgs'), ('60 kgs', '60 kgs'), ('70 kgs', '70 kgs'), ('50 kgs', '50 kgs'), ('90 kgs', '90 kgs')], max_length=100),
        ),
        migrations.AlterField(
            model_name='verduras',
            name='ciudad',
            field=models.CharField(choices=[('cartagena', 'cartagena'), ('zipaquira', 'zipaquira'), ('bogota', 'bogota'), ('cali', 'cali'), ('caucasia', 'caucasia'), ('el carmen de bolivar', 'el carmen de bolivar'), ('facatativa', 'facatativa'), ('boyaca', 'boyaca'), ('tunja', 'tunja'), ('barranquilla', 'barranquilla'), ('turbo', 'turbo'), ('leticia', 'leticia'), ('medellin', 'medellin'), ('rionegro', 'rionegro'), ('sabanalarga', 'sabanalarga'), ('girardot', 'girardot'), ('fusagasuga', 'fusagasuga'), ('cucuta', 'cucuta'), ('apartado', 'apartado'), ('arauca', 'arauca'), ('magangue', 'magangue')], max_length=50),
        ),
        migrations.AlterField(
            model_name='verduras',
            name='producto',
            field=models.CharField(choices=[('aguacate', 'aguacate'), ('rabano', 'rabano'), ('bruselas', 'bruselas'), ('zanahoria', 'zanahoria'), ('pimenton', 'pimenton'), ('coliflor', 'coliflor'), ('habichuela', 'habichuela'), ('arbeja', 'arbeja'), ('champiñon', 'champiñon'), ('acelga', 'acelga'), ('apio', 'apio'), ('remolacha', 'remolacha'), ('brocoli', 'brocoli'), ('berenjena', 'berenjena'), ('cebolla larga', 'cebolla larga'), ('cebolla cabezona', 'cebolla cabezona'), ('tomate', 'tomate'), ('lechuga', 'lechuga'), ('zukini', 'zukini'), ('pepino', 'pepino'), ('cilantro', 'cilantro'), ('ahuyama', 'ahuyama'), ('repollo', 'repollo'), ('espinaca', 'espinaca')], max_length=100),
        ),
    ]
