# Generated by Django 4.1.3 on 2022-12-12 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_alter_abarrotes_cantidad_alter_abarrotes_ciudad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abarrotes',
            name='cantidad',
            field=models.CharField(choices=[('100 kgs', '100 kgs'), ('70 kgs', '70 kgs'), ('80 kgs', '80 kgs'), ('60 kgs', '60 kgs'), ('90 kgs', '90 kgs'), ('50 kgs', '50 kgs')], max_length=100),
        ),
        migrations.AlterField(
            model_name='abarrotes',
            name='ciudad',
            field=models.CharField(choices=[('zipaquira', 'zipaquira'), ('bogota', 'bogota'), ('magangue', 'magangue'), ('girardot', 'girardot'), ('facatativa', 'facatativa'), ('apartado', 'apartado'), ('turbo', 'turbo'), ('barranquilla', 'barranquilla'), ('cucuta', 'cucuta'), ('medellin', 'medellin'), ('sabanalarga', 'sabanalarga'), ('el carmen de bolivar', 'el carmen de bolivar'), ('cartagena', 'cartagena'), ('arauca', 'arauca'), ('rionegro', 'rionegro'), ('cali', 'cali'), ('caucasia', 'caucasia'), ('tunja', 'tunja'), ('boyaca', 'boyaca'), ('leticia', 'leticia'), ('fusagasuga', 'fusagasuga')], max_length=50),
        ),
        migrations.AlterField(
            model_name='abarrotes',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'pendiente'), ('no disponible', 'no disponible'), ('Disponible', 'disponible')], max_length=50),
        ),
        migrations.AlterField(
            model_name='abarrotes',
            name='ofrece_transporte',
            field=models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], max_length=254),
        ),
        migrations.AlterField(
            model_name='abarrotes',
            name='producto',
            field=models.CharField(choices=[('compota', 'compota'), ('aceite', 'aceite'), ('miel', 'miel'), ('mayonesa', 'mayonesa'), ('vinagre', 'vinagre'), ('sal', 'sal'), ('gelatina', 'gelatina')], max_length=100),
        ),
        migrations.AlterField(
            model_name='carnes',
            name='cantidad',
            field=models.CharField(choices=[('100 kgs', '100 kgs'), ('70 kgs', '70 kgs'), ('80 kgs', '80 kgs'), ('60 kgs', '60 kgs'), ('90 kgs', '90 kgs'), ('50 kgs', '50 kgs')], max_length=100),
        ),
        migrations.AlterField(
            model_name='carnes',
            name='ciudad',
            field=models.CharField(choices=[('zipaquira', 'zipaquira'), ('bogota', 'bogota'), ('magangue', 'magangue'), ('girardot', 'girardot'), ('facatativa', 'facatativa'), ('apartado', 'apartado'), ('turbo', 'turbo'), ('barranquilla', 'barranquilla'), ('cucuta', 'cucuta'), ('medellin', 'medellin'), ('sabanalarga', 'sabanalarga'), ('el carmen de bolivar', 'el carmen de bolivar'), ('cartagena', 'cartagena'), ('arauca', 'arauca'), ('rionegro', 'rionegro'), ('cali', 'cali'), ('caucasia', 'caucasia'), ('tunja', 'tunja'), ('boyaca', 'boyaca'), ('leticia', 'leticia'), ('fusagasuga', 'fusagasuga')], max_length=50),
        ),
        migrations.AlterField(
            model_name='carnes',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'pendiente'), ('no disponible', 'no disponible'), ('Disponible', 'disponible')], max_length=50),
        ),
        migrations.AlterField(
            model_name='carnes',
            name='ofrece_transporte',
            field=models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], max_length=254),
        ),
        migrations.AlterField(
            model_name='carnes',
            name='producto',
            field=models.CharField(choices=[('carne_vaca', 'carne_vaca'), ('pecho', 'pecho'), ('cadera_res', 'cadera_res'), ('carne_cerdo', 'carne_cerdo'), ('sobre_barriga', 'sobre_barriga'), ('punta_de_anca', 'punta_de_anca'), ('carne_térnera', 'carne_térnera'), ('costillas_res', 'costillas_res'), ('solomito', 'solomito'), ('carne_pollo', 'carne_pollo'), ('pescado', 'pescado')], max_length=100),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cedula',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='ciudad',
            field=models.CharField(choices=[('zipaquira', 'zipaquira'), ('bogota', 'bogota'), ('magangue', 'magangue'), ('girardot', 'girardot'), ('facatativa', 'facatativa'), ('apartado', 'apartado'), ('turbo', 'turbo'), ('barranquilla', 'barranquilla'), ('cucuta', 'cucuta'), ('medellin', 'medellin'), ('sabanalarga', 'sabanalarga'), ('el carmen de bolivar', 'el carmen de bolivar'), ('cartagena', 'cartagena'), ('arauca', 'arauca'), ('rionegro', 'rionegro'), ('cali', 'cali'), ('caucasia', 'caucasia'), ('tunja', 'tunja'), ('boyaca', 'boyaca'), ('leticia', 'leticia'), ('fusagasuga', 'fusagasuga')], max_length=40),
        ),
        migrations.AlterField(
            model_name='conductor',
            name='cedula',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='conductor',
            name='ciudad',
            field=models.CharField(choices=[('zipaquira', 'zipaquira'), ('bogota', 'bogota'), ('magangue', 'magangue'), ('girardot', 'girardot'), ('facatativa', 'facatativa'), ('apartado', 'apartado'), ('turbo', 'turbo'), ('barranquilla', 'barranquilla'), ('cucuta', 'cucuta'), ('medellin', 'medellin'), ('sabanalarga', 'sabanalarga'), ('el carmen de bolivar', 'el carmen de bolivar'), ('cartagena', 'cartagena'), ('arauca', 'arauca'), ('rionegro', 'rionegro'), ('cali', 'cali'), ('caucasia', 'caucasia'), ('tunja', 'tunja'), ('boyaca', 'boyaca'), ('leticia', 'leticia'), ('fusagasuga', 'fusagasuga')], max_length=40),
        ),
        migrations.AlterField(
            model_name='frutas',
            name='cantidad',
            field=models.CharField(choices=[('100 kgs', '100 kgs'), ('70 kgs', '70 kgs'), ('80 kgs', '80 kgs'), ('60 kgs', '60 kgs'), ('90 kgs', '90 kgs'), ('50 kgs', '50 kgs')], max_length=100),
        ),
        migrations.AlterField(
            model_name='frutas',
            name='ciudad',
            field=models.CharField(choices=[('zipaquira', 'zipaquira'), ('bogota', 'bogota'), ('magangue', 'magangue'), ('girardot', 'girardot'), ('facatativa', 'facatativa'), ('apartado', 'apartado'), ('turbo', 'turbo'), ('barranquilla', 'barranquilla'), ('cucuta', 'cucuta'), ('medellin', 'medellin'), ('sabanalarga', 'sabanalarga'), ('el carmen de bolivar', 'el carmen de bolivar'), ('cartagena', 'cartagena'), ('arauca', 'arauca'), ('rionegro', 'rionegro'), ('cali', 'cali'), ('caucasia', 'caucasia'), ('tunja', 'tunja'), ('boyaca', 'boyaca'), ('leticia', 'leticia'), ('fusagasuga', 'fusagasuga')], max_length=50),
        ),
        migrations.AlterField(
            model_name='frutas',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'pendiente'), ('no disponible', 'no disponible'), ('Disponible', 'disponible')], max_length=50),
        ),
        migrations.AlterField(
            model_name='frutas',
            name='ofrece_transporte',
            field=models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], max_length=254),
        ),
        migrations.AlterField(
            model_name='frutas',
            name='producto',
            field=models.CharField(choices=[('frambueza', 'frambueza'), ('fresa', 'fresa'), ('uvas', 'uvas'), ('durazno', 'durazno'), ('uva', 'uva'), ('arandanos', 'arandanos'), ('melon', 'melon'), ('pera', 'pera'), ('mandarina', 'mandarina'), ('manzana', 'manzana'), ('maracuya', 'maracuya'), ('ciruela', 'ciruela'), ('mora', 'mora'), ('kiwi', 'kiwi'), ('sandia', 'sandia'), ('piña', 'piña'), ('guanabana', 'guanabana'), ('cereza', 'cereza'), ('naranja', 'naranja'), ('granadilla', 'granadilla'), ('pitaya', 'pitaya'), ('papaya', 'papaya'), ('mango', 'mango'), ('banano', 'banano'), ('limon', 'limon')], max_length=100),
        ),
        migrations.AlterField(
            model_name='granos',
            name='cantidad',
            field=models.CharField(choices=[('100 kgs', '100 kgs'), ('70 kgs', '70 kgs'), ('80 kgs', '80 kgs'), ('60 kgs', '60 kgs'), ('90 kgs', '90 kgs'), ('50 kgs', '50 kgs')], max_length=100),
        ),
        migrations.AlterField(
            model_name='granos',
            name='ciudad',
            field=models.CharField(choices=[('zipaquira', 'zipaquira'), ('bogota', 'bogota'), ('magangue', 'magangue'), ('girardot', 'girardot'), ('facatativa', 'facatativa'), ('apartado', 'apartado'), ('turbo', 'turbo'), ('barranquilla', 'barranquilla'), ('cucuta', 'cucuta'), ('medellin', 'medellin'), ('sabanalarga', 'sabanalarga'), ('el carmen de bolivar', 'el carmen de bolivar'), ('cartagena', 'cartagena'), ('arauca', 'arauca'), ('rionegro', 'rionegro'), ('cali', 'cali'), ('caucasia', 'caucasia'), ('tunja', 'tunja'), ('boyaca', 'boyaca'), ('leticia', 'leticia'), ('fusagasuga', 'fusagasuga')], max_length=50),
        ),
        migrations.AlterField(
            model_name='granos',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'pendiente'), ('no disponible', 'no disponible'), ('Disponible', 'disponible')], max_length=50),
        ),
        migrations.AlterField(
            model_name='granos',
            name='ofrece_transporte',
            field=models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], max_length=254),
        ),
        migrations.AlterField(
            model_name='granos',
            name='producto',
            field=models.CharField(choices=[('avellana', 'avellana'), ('quinua', 'quinua'), ('nuez', 'nuez'), ('mani', 'mani'), ('amaranto', 'amaranto'), ('almendras', 'almendras'), ('trigoo', 'trigoo')], max_length=100),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='cantidad',
            field=models.CharField(choices=[('100 kgs', '100 kgs'), ('70 kgs', '70 kgs'), ('80 kgs', '80 kgs'), ('60 kgs', '60 kgs'), ('90 kgs', '90 kgs'), ('50 kgs', '50 kgs')], max_length=254),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='ciudad',
            field=models.CharField(choices=[('zipaquira', 'zipaquira'), ('bogota', 'bogota'), ('magangue', 'magangue'), ('girardot', 'girardot'), ('facatativa', 'facatativa'), ('apartado', 'apartado'), ('turbo', 'turbo'), ('barranquilla', 'barranquilla'), ('cucuta', 'cucuta'), ('medellin', 'medellin'), ('sabanalarga', 'sabanalarga'), ('el carmen de bolivar', 'el carmen de bolivar'), ('cartagena', 'cartagena'), ('arauca', 'arauca'), ('rionegro', 'rionegro'), ('cali', 'cali'), ('caucasia', 'caucasia'), ('tunja', 'tunja'), ('boyaca', 'boyaca'), ('leticia', 'leticia'), ('fusagasuga', 'fusagasuga')], max_length=254),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'pendiente'), ('no disponible', 'no disponible'), ('Disponible', 'disponible')], max_length=254),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='ofrece_transporte',
            field=models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], max_length=254),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='producto',
            field=models.CharField(choices=[('frambueza', 'frambueza'), ('fresa', 'fresa'), ('uvas', 'uvas'), ('durazno', 'durazno'), ('uva', 'uva'), ('arandanos', 'arandanos'), ('melon', 'melon'), ('pera', 'pera'), ('mandarina', 'mandarina'), ('manzana', 'manzana'), ('maracuya', 'maracuya'), ('ciruela', 'ciruela'), ('mora', 'mora'), ('kiwi', 'kiwi'), ('sandia', 'sandia'), ('piña', 'piña'), ('guanabana', 'guanabana'), ('cereza', 'cereza'), ('naranja', 'naranja'), ('granadilla', 'granadilla'), ('pitaya', 'pitaya'), ('papaya', 'papaya'), ('mango', 'mango'), ('banano', 'banano'), ('limon', 'limon')], max_length=254),
        ),
        migrations.AlterField(
            model_name='lacteos',
            name='cantidad',
            field=models.CharField(choices=[('100 kgs', '100 kgs'), ('70 kgs', '70 kgs'), ('80 kgs', '80 kgs'), ('60 kgs', '60 kgs'), ('90 kgs', '90 kgs'), ('50 kgs', '50 kgs')], max_length=100),
        ),
        migrations.AlterField(
            model_name='lacteos',
            name='ciudad',
            field=models.CharField(choices=[('zipaquira', 'zipaquira'), ('bogota', 'bogota'), ('magangue', 'magangue'), ('girardot', 'girardot'), ('facatativa', 'facatativa'), ('apartado', 'apartado'), ('turbo', 'turbo'), ('barranquilla', 'barranquilla'), ('cucuta', 'cucuta'), ('medellin', 'medellin'), ('sabanalarga', 'sabanalarga'), ('el carmen de bolivar', 'el carmen de bolivar'), ('cartagena', 'cartagena'), ('arauca', 'arauca'), ('rionegro', 'rionegro'), ('cali', 'cali'), ('caucasia', 'caucasia'), ('tunja', 'tunja'), ('boyaca', 'boyaca'), ('leticia', 'leticia'), ('fusagasuga', 'fusagasuga')], max_length=50),
        ),
        migrations.AlterField(
            model_name='lacteos',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'pendiente'), ('no disponible', 'no disponible'), ('Disponible', 'disponible')], max_length=50),
        ),
        migrations.AlterField(
            model_name='lacteos',
            name='ofrece_transporte',
            field=models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], max_length=254),
        ),
        migrations.AlterField(
            model_name='lacteos',
            name='producto',
            field=models.CharField(choices=[('Huevosgallina_campera', 'Huevosgallina_campera'), ('yogur', 'yogur'), ('Huevosgallinas_en_jaulas', 'Huevosgallinas_en_jaulas'), ('huevos_codorniz', 'huevos_codorniz'), ('huevos_AA', 'huevos_AA'), ('kumis', 'kumis'), ('huevosAAA', 'huevosAAA')], max_length=100),
        ),
        migrations.AlterField(
            model_name='leguminosas',
            name='cantidad',
            field=models.CharField(choices=[('100 kgs', '100 kgs'), ('70 kgs', '70 kgs'), ('80 kgs', '80 kgs'), ('60 kgs', '60 kgs'), ('90 kgs', '90 kgs'), ('50 kgs', '50 kgs')], max_length=100),
        ),
        migrations.AlterField(
            model_name='leguminosas',
            name='ciudad',
            field=models.CharField(choices=[('zipaquira', 'zipaquira'), ('bogota', 'bogota'), ('magangue', 'magangue'), ('girardot', 'girardot'), ('facatativa', 'facatativa'), ('apartado', 'apartado'), ('turbo', 'turbo'), ('barranquilla', 'barranquilla'), ('cucuta', 'cucuta'), ('medellin', 'medellin'), ('sabanalarga', 'sabanalarga'), ('el carmen de bolivar', 'el carmen de bolivar'), ('cartagena', 'cartagena'), ('arauca', 'arauca'), ('rionegro', 'rionegro'), ('cali', 'cali'), ('caucasia', 'caucasia'), ('tunja', 'tunja'), ('boyaca', 'boyaca'), ('leticia', 'leticia'), ('fusagasuga', 'fusagasuga')], max_length=50),
        ),
        migrations.AlterField(
            model_name='leguminosas',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'pendiente'), ('no disponible', 'no disponible'), ('Disponible', 'disponible')], max_length=50),
        ),
        migrations.AlterField(
            model_name='leguminosas',
            name='ofrece_transporte',
            field=models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], max_length=254),
        ),
        migrations.AlterField(
            model_name='productor',
            name='cedula',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='productor',
            name='ciudad',
            field=models.CharField(choices=[('zipaquira', 'zipaquira'), ('bogota', 'bogota'), ('magangue', 'magangue'), ('girardot', 'girardot'), ('facatativa', 'facatativa'), ('apartado', 'apartado'), ('turbo', 'turbo'), ('barranquilla', 'barranquilla'), ('cucuta', 'cucuta'), ('medellin', 'medellin'), ('sabanalarga', 'sabanalarga'), ('el carmen de bolivar', 'el carmen de bolivar'), ('cartagena', 'cartagena'), ('arauca', 'arauca'), ('rionegro', 'rionegro'), ('cali', 'cali'), ('caucasia', 'caucasia'), ('tunja', 'tunja'), ('boyaca', 'boyaca'), ('leticia', 'leticia'), ('fusagasuga', 'fusagasuga')], max_length=40),
        ),
        migrations.AlterField(
            model_name='productos',
            name='cantidad',
            field=models.CharField(choices=[('100 kgs', '100 kgs'), ('70 kgs', '70 kgs'), ('80 kgs', '80 kgs'), ('60 kgs', '60 kgs'), ('90 kgs', '90 kgs'), ('50 kgs', '50 kgs')], max_length=254),
        ),
        migrations.AlterField(
            model_name='productos',
            name='ciudad',
            field=models.CharField(choices=[('zipaquira', 'zipaquira'), ('bogota', 'bogota'), ('magangue', 'magangue'), ('girardot', 'girardot'), ('facatativa', 'facatativa'), ('apartado', 'apartado'), ('turbo', 'turbo'), ('barranquilla', 'barranquilla'), ('cucuta', 'cucuta'), ('medellin', 'medellin'), ('sabanalarga', 'sabanalarga'), ('el carmen de bolivar', 'el carmen de bolivar'), ('cartagena', 'cartagena'), ('arauca', 'arauca'), ('rionegro', 'rionegro'), ('cali', 'cali'), ('caucasia', 'caucasia'), ('tunja', 'tunja'), ('boyaca', 'boyaca'), ('leticia', 'leticia'), ('fusagasuga', 'fusagasuga')], max_length=254),
        ),
        migrations.AlterField(
            model_name='productos',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'pendiente'), ('no disponible', 'no disponible'), ('Disponible', 'disponible')], max_length=254),
        ),
        migrations.AlterField(
            model_name='productos',
            name='ofrece_transporte',
            field=models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], max_length=254),
        ),
        migrations.AlterField(
            model_name='productos',
            name='producto',
            field=models.CharField(choices=[('frambueza', 'frambueza'), ('fresa', 'fresa'), ('uvas', 'uvas'), ('durazno', 'durazno'), ('uva', 'uva'), ('arandanos', 'arandanos'), ('melon', 'melon'), ('pera', 'pera'), ('mandarina', 'mandarina'), ('manzana', 'manzana'), ('maracuya', 'maracuya'), ('ciruela', 'ciruela'), ('mora', 'mora'), ('kiwi', 'kiwi'), ('sandia', 'sandia'), ('piña', 'piña'), ('guanabana', 'guanabana'), ('cereza', 'cereza'), ('naranja', 'naranja'), ('granadilla', 'granadilla'), ('pitaya', 'pitaya'), ('papaya', 'papaya'), ('mango', 'mango'), ('banano', 'banano'), ('limon', 'limon')], max_length=254),
        ),
        migrations.AlterField(
            model_name='registro',
            name='ciudad',
            field=models.CharField(choices=[('zipaquira', 'zipaquira'), ('bogota', 'bogota'), ('magangue', 'magangue'), ('girardot', 'girardot'), ('facatativa', 'facatativa'), ('apartado', 'apartado'), ('turbo', 'turbo'), ('barranquilla', 'barranquilla'), ('cucuta', 'cucuta'), ('medellin', 'medellin'), ('sabanalarga', 'sabanalarga'), ('el carmen de bolivar', 'el carmen de bolivar'), ('cartagena', 'cartagena'), ('arauca', 'arauca'), ('rionegro', 'rionegro'), ('cali', 'cali'), ('caucasia', 'caucasia'), ('tunja', 'tunja'), ('boyaca', 'boyaca'), ('leticia', 'leticia'), ('fusagasuga', 'fusagasuga')], max_length=40),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='capacidad',
            field=models.CharField(choices=[('10_TONELADA', '10_TONELADA'), ('9_TONELADA', '9_TONELADA'), ('13_TONOLEDA', '13_TONOLEDA'), ('7_TONELADA', '7_TONELADA'), ('30_TONOLEDA', '30_TONOLEDA'), ('15_TONELADA', '15_TONELADA'), ('21_TONELADA', '21_TONELADA'), ('11_TONOLEDA', '11_TONOLEDA'), ('27_TONOLEDA', '27_TONOLEDA'), ('3_TONOLEDA', '3_TONOLEDA'), ('2_TONELADA', '2_TONELADA'), ('4_TONELADA', '4_TONELADA'), ('24_TONELADA', '24_TONELADA'), ('1_TONELADA', '1_TONELADA'), ('500_KGS', '500_KGS'), ('12_TONELADA', '12_TONELADA'), ('18_TONOLEDA', '18_TONOLEDA'), ('8_TONOLEDA', '8_TONOLEDA'), ('32_TONOLEDA', '32_TONOLEDA'), ('6_TONOLEDA', '6_TONOLEDA'), ('5_TONELADA', '5_TONELADA')], max_length=100),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='color',
            field=models.CharField(choices=[('dorado', 'dorado'), ('morado', 'morado'), ('rojo', 'rojo'), ('cafe', 'cafe'), ('negro', 'negro'), ('perlado', 'perlado'), ('naranja', 'naranja'), ('azul', 'azul'), ('rosado', 'rosado'), ('blanco', 'blanco'), ('gris', 'gris'), ('amarillo', 'amarillo')], max_length=100),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='marca',
            field=models.CharField(choices=[('HIUNDAY', 'HIUNDAY'), ('FORD', 'FORD'), ('NISSAN', 'NISSAN'), ('MAZDA', 'MAZDA'), ('CHEVROLET', 'CHEVROLET'), ('KIA', 'KIA'), ('TOYOTA', 'TOYOTA')], max_length=254),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='tipo_carroceria',
            field=models.CharField(choices=[('platon', 'platon'), ('estacas', 'estacas'), ('termoquin', 'termoquin'), ('furgon', 'furgon')], max_length=100),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='tipo_vehiculo',
            field=models.CharField(choices=[('Cuatro manos', 'Cuatro manos'), ('Tractomula 2 troques', 'Tractomula 2 troques'), ('Camion grande', 'Camion grande'), ('Turbo', 'Turbo'), ('Minimula', 'Minimula'), ('Tractomula 3 troques', 'Tractomula 3 troques'), ('Doble troque', 'Doble troque'), ('Luv', 'Luv'), ('Camion sencillo', 'Camion sencillo')], max_length=100),
        ),
        migrations.AlterField(
            model_name='verduras',
            name='cantidad',
            field=models.CharField(choices=[('100 kgs', '100 kgs'), ('70 kgs', '70 kgs'), ('80 kgs', '80 kgs'), ('60 kgs', '60 kgs'), ('90 kgs', '90 kgs'), ('50 kgs', '50 kgs')], max_length=100),
        ),
        migrations.AlterField(
            model_name='verduras',
            name='ciudad',
            field=models.CharField(choices=[('zipaquira', 'zipaquira'), ('bogota', 'bogota'), ('magangue', 'magangue'), ('girardot', 'girardot'), ('facatativa', 'facatativa'), ('apartado', 'apartado'), ('turbo', 'turbo'), ('barranquilla', 'barranquilla'), ('cucuta', 'cucuta'), ('medellin', 'medellin'), ('sabanalarga', 'sabanalarga'), ('el carmen de bolivar', 'el carmen de bolivar'), ('cartagena', 'cartagena'), ('arauca', 'arauca'), ('rionegro', 'rionegro'), ('cali', 'cali'), ('caucasia', 'caucasia'), ('tunja', 'tunja'), ('boyaca', 'boyaca'), ('leticia', 'leticia'), ('fusagasuga', 'fusagasuga')], max_length=50),
        ),
        migrations.AlterField(
            model_name='verduras',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'pendiente'), ('no disponible', 'no disponible'), ('Disponible', 'disponible')], max_length=50),
        ),
        migrations.AlterField(
            model_name='verduras',
            name='ofrece_transporte',
            field=models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], max_length=254),
        ),
        migrations.AlterField(
            model_name='verduras',
            name='producto',
            field=models.CharField(choices=[('arbeja', 'arbeja'), ('tomate', 'tomate'), ('espinaca', 'espinaca'), ('habichuela', 'habichuela'), ('ahuyama', 'ahuyama'), ('remolacha', 'remolacha'), ('coliflor', 'coliflor'), ('cebolla cabezona', 'cebolla cabezona'), ('rabano', 'rabano'), ('cilantro', 'cilantro'), ('acelga', 'acelga'), ('brocoli', 'brocoli'), ('champiñon', 'champiñon'), ('cebolla larga', 'cebolla larga'), ('berenjena', 'berenjena'), ('repollo', 'repollo'), ('zanahoria', 'zanahoria'), ('zukini', 'zukini'), ('bruselas', 'bruselas'), ('pimenton', 'pimenton'), ('apio', 'apio'), ('aguacate', 'aguacate'), ('pepino', 'pepino'), ('lechuga', 'lechuga')], max_length=100),
        ),
    ]
