# Generated by Django 4.1.3 on 2022-11-22 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_alter_driver_vehicle_type_alter_registro_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='vehicle_type',
            field=models.CharField(choices=[('Tractomula 2 troques', 'Tractomula 2 troques'), ('Minimula', 'Minimula'), ('Pickup', 'Pickup'), ('Tractomula 3 troques', 'Tractomula 3 troques'), ('Luv', 'Luv'), ('Turbo', 'Turbo'), ('Camion sencillo', 'Camion'), ('Doble troque', 'Doble troque'), ('Cuatro manos', 'Cuatro manos')], max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='registro',
            name='username',
            field=models.CharField(max_length=254, unique=True),
        ),
    ]
