# Generated by Django 4.1.3 on 2022-11-22 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_alter_driver_vehicle_type_alter_registro_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('shirt_size', models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], max_length=1)),
            ],
        ),
        migrations.AlterField(
            model_name='driver',
            name='vehicle_type',
            field=models.CharField(choices=[('Pickup', 'Pickup'), ('Luv', 'Luv'), ('Turbo', 'Turbo'), ('Camion sencillo', 'Camion'), ('Doble troque', 'Doble troque'), ('Cuatro manos', 'Cuatro manos'), ('Minimula', 'Minimula'), ('Tractomula 2 troques', 'Tractomula 2 troques'), ('Tractomula 3 troques', 'Tractomula 3 troques')], max_length=254, null=True),
        ),
    ]
