# Generated by Django 4.1.3 on 2022-11-22 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_person_alter_driver_vehicle_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='soporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo', models.CharField(max_length=50)),
                ('comentario', models.CharField(max_length=500)),
            ],
        ),
    ]
