# Generated by Django 4.1.3 on 2022-11-22 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_soporte'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='soporte',
            table='soporte',
        ),
    ]
