# Generated by Django 4.1.3 on 2022-11-29 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_alter_soporte_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=254, unique=True)),
                ('categoria', models.CharField(max_length=254)),
            ],
            options={
                'db_table': 'productos',
            },
        ),
    ]
