# Generated by Django 4.1.3 on 2022-12-04 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0012_delete_login_delete_productos'),
    ]

    operations = [
        migrations.CreateModel(
            name='productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=254, unique=True)),
                ('ciudad', models.CharField(max_length=254)),
                ('fecha_disponibilidad', models.DateTimeField(auto_now_add=True)),
                ('ofrece_trasporte', models.CharField(max_length=254)),
                ('descripcion', models.CharField(max_length=254)),
            ],
            options={
                'db_table': 'productos',
            },
        ),
    ]
