# Generated by Django 4.1.3 on 2022-12-05 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0014_prueba_delete_productos'),
    ]

    operations = [
        migrations.DeleteModel(
            name='registro',
        ),
        migrations.AlterField(
            model_name='prueba',
            name='ciudad',
            field=models.CharField(choices=[('medellin', 'medellin'), ('cali', 'cali'), ('barranquilla', 'barranquilla'), ('bogota', 'bogota')], max_length=50, null=True),
        ),
    ]
