# Generated by Django 4.1.3 on 2022-12-05 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0015_delete_registro_alter_prueba_ciudad'),
    ]

    operations = [
        migrations.CreateModel(
            name='registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=254)),
                ('rol', models.CharField(choices=[('eres cliente', 'eres cliente'), ('eres productor', 'eres productor'), ('eres conductor', 'eres conducto')], max_length=254)),
                ('nombres', models.CharField(max_length=254)),
                ('apellidos', models.CharField(max_length=254)),
                ('cedula', models.CharField(max_length=254)),
                ('direcion', models.CharField(max_length=254)),
                ('telefono', models.CharField(max_length=254)),
                ('celular', models.CharField(max_length=254)),
                ('correo', models.CharField(max_length=254)),
                ('ciudad', models.CharField(choices=[('cali', 'cali'), ('sabanalarga', 'sabanalarga'), ('tunja', 'tunja'), ('turbo', 'turbo'), ('el carmen de bolivar', 'el carmen de bolivar'), ('cucuta', 'cucuta'), ('zipaquira', 'zipaquira'), ('fusagasuga', 'fusagasuga'), ('facatativa', 'facatativa'), ('leticia', 'leticia'), ('caucasia', 'caucasia'), ('magangue', 'magangue'), ('girardot', 'girardot'), ('apartado', 'apartado'), ('bogota', 'bogota'), ('cartagena', 'cartagena'), ('boyaca', 'boyaca'), ('medellin', 'medellin'), ('rionegro', 'rionegro'), ('barranquilla', 'barranquilla'), ('arauca', 'arauca')], max_length=40)),
            ],
            options={
                'db_table': 'registro',
            },
        ),
        migrations.AlterField(
            model_name='prueba',
            name='ciudad',
            field=models.CharField(choices=[('cali', 'cali'), ('medellin', 'medellin'), ('barranquilla', 'barranquilla'), ('bogota', 'bogota')], max_length=50, null=True),
        ),
    ]
