# Generated by Django 4.1.3 on 2022-12-07 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0016_registro_alter_prueba_ciudad'),
    ]

    operations = [
        migrations.CreateModel(
            name='productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(choices=[('uvas', 'uvas'), ('mandarina', 'mandarina'), ('manzana', 'manzana'), ('papaya', 'papaya'), ('banano', 'banano'), ('fresa', 'fresa')], max_length=254)),
                ('cantidad', models.CharField(choices=[('70 kgs', '70 kgs'), ('80 kgs', '80 kgs'), ('90 kgs', '90 kgs'), ('100 kgs', '100 kgs'), ('50 kgs', '50 kgs'), ('60 kgs', '60 kgs')], max_length=254)),
                ('precio_kgs', models.CharField(max_length=254)),
                ('precio_total', models.CharField(max_length=254)),
                ('ciudad', models.CharField(choices=[('medellin', 'medellin'), ('cali', 'cali'), ('zipaquira', 'zipaquira'), ('arauca', 'arauca'), ('rionegro', 'rionegro'), ('girardot', 'girardot'), ('fusagasuga', 'fusagasuga'), ('cucuta', 'cucuta'), ('el carmen de bolivar', 'el carmen de bolivar'), ('apartado', 'apartado'), ('boyaca', 'boyaca'), ('cartagena', 'cartagena'), ('bogota', 'bogota'), ('leticia', 'leticia'), ('sabanalarga', 'sabanalarga'), ('caucasia', 'caucasia'), ('facatativa', 'facatativa'), ('magangue', 'magangue'), ('barranquilla', 'barranquilla'), ('turbo', 'turbo'), ('tunja', 'tunja')], max_length=254)),
                ('fecha_disponible', models.CharField(max_length=254)),
                ('ofrece_transporte', models.CharField(choices=[('NO', 'NO'), ('SI', 'SI')], max_length=254)),
                ('descripcion', models.CharField(max_length=254)),
                ('estado', models.CharField(choices=[('no disponible', 'no disponible'), ('pendiente', 'pendiente'), ('Disponible', 'disponible')], max_length=254)),
            ],
            options={
                'db_table': 'productos',
            },
        ),
        migrations.DeleteModel(
            name='prueba',
        ),
        migrations.AlterField(
            model_name='registro',
            name='ciudad',
            field=models.CharField(choices=[('medellin', 'medellin'), ('cali', 'cali'), ('zipaquira', 'zipaquira'), ('arauca', 'arauca'), ('rionegro', 'rionegro'), ('girardot', 'girardot'), ('fusagasuga', 'fusagasuga'), ('cucuta', 'cucuta'), ('el carmen de bolivar', 'el carmen de bolivar'), ('apartado', 'apartado'), ('boyaca', 'boyaca'), ('cartagena', 'cartagena'), ('bogota', 'bogota'), ('leticia', 'leticia'), ('sabanalarga', 'sabanalarga'), ('caucasia', 'caucasia'), ('facatativa', 'facatativa'), ('magangue', 'magangue'), ('barranquilla', 'barranquilla'), ('turbo', 'turbo'), ('tunja', 'tunja')], max_length=40),
        ),
        migrations.AlterField(
            model_name='registro',
            name='rol',
            field=models.CharField(choices=[('eres productor', 'eres productor'), ('eres conductor', 'eres conducto'), ('eres cliente', 'eres cliente')], max_length=254),
        ),
    ]
