# Generated by Django 4.1.3 on 2022-12-07 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0018_inventario_alter_productos_cantidad_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='frutas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(max_length=254)),
                ('cantidad', models.CharField(max_length=254)),
                ('precio_kgs', models.CharField(max_length=254)),
                ('precio_total', models.CharField(max_length=254)),
                ('ciudad', models.CharField(max_length=254)),
                ('fecha_disponible', models.CharField(max_length=254)),
                ('ofrece_transporte', models.CharField(max_length=254)),
                ('descripcion', models.CharField(max_length=254)),
                ('estado', models.CharField(max_length=254)),
            ],
            options={
                'db_table': 'frutas',
            },
        ),
        migrations.CreateModel(
            name='granos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(max_length=254)),
                ('cantidad', models.CharField(max_length=254)),
                ('precio_kgs', models.CharField(max_length=254)),
                ('precio_total', models.CharField(max_length=254)),
                ('ciudad', models.CharField(max_length=254)),
                ('fecha_disponible', models.CharField(max_length=254)),
                ('ofrece_transporte', models.CharField(max_length=254)),
                ('descripcion', models.CharField(max_length=254)),
                ('estado', models.CharField(max_length=254)),
            ],
            options={
                'db_table': 'granos',
            },
        ),
        migrations.CreateModel(
            name='legumbres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(max_length=254)),
                ('cantidad', models.CharField(max_length=254)),
                ('precio_kgs', models.CharField(max_length=254)),
                ('precio_total', models.CharField(max_length=254)),
                ('ciudad', models.CharField(max_length=254)),
                ('fecha_disponible', models.CharField(max_length=254)),
                ('ofrece_transporte', models.CharField(max_length=254)),
                ('descripcion', models.CharField(max_length=254)),
                ('estado', models.CharField(max_length=254)),
            ],
            options={
                'db_table': 'legumbres',
            },
        ),
        migrations.CreateModel(
            name='verduras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(max_length=254)),
                ('cantidad', models.CharField(max_length=254)),
                ('precio_kgs', models.CharField(max_length=254)),
                ('precio_total', models.CharField(max_length=254)),
                ('ciudad', models.CharField(max_length=254)),
                ('fecha_disponible', models.CharField(max_length=254)),
                ('ofrece_transporte', models.CharField(max_length=254)),
                ('descripcion', models.CharField(max_length=254)),
                ('estado', models.CharField(max_length=254)),
            ],
            options={
                'db_table': 'verduras',
            },
        ),
        migrations.AlterField(
            model_name='productos',
            name='cantidad',
            field=models.CharField(choices=[('100 kgs', '100 kgs'), ('70 kgs', '70 kgs'), ('60 kgs', '60 kgs'), ('50 kgs', '50 kgs'), ('90 kgs', '90 kgs'), ('80 kgs', '80 kgs')], max_length=254),
        ),
        migrations.AlterField(
            model_name='productos',
            name='ciudad',
            field=models.CharField(choices=[('girardot', 'girardot'), ('leticia', 'leticia'), ('apartado', 'apartado'), ('tunja', 'tunja'), ('bogota', 'bogota'), ('cucuta', 'cucuta'), ('turbo', 'turbo'), ('cartagena', 'cartagena'), ('facatativa', 'facatativa'), ('fusagasuga', 'fusagasuga'), ('cali', 'cali'), ('zipaquira', 'zipaquira'), ('medellin', 'medellin'), ('sabanalarga', 'sabanalarga'), ('boyaca', 'boyaca'), ('el carmen de bolivar', 'el carmen de bolivar'), ('barranquilla', 'barranquilla'), ('magangue', 'magangue'), ('arauca', 'arauca'), ('caucasia', 'caucasia'), ('rionegro', 'rionegro')], max_length=254),
        ),
        migrations.AlterField(
            model_name='productos',
            name='ofrece_transporte',
            field=models.CharField(choices=[('NO', 'NO'), ('SI', 'SI')], max_length=254),
        ),
        migrations.AlterField(
            model_name='productos',
            name='producto',
            field=models.CharField(choices=[('manzana', 'manzana'), ('banano', 'banano'), ('fresa', 'fresa'), ('papaya', 'papaya'), ('uvas', 'uvas'), ('mandarina', 'mandarina')], max_length=254),
        ),
        migrations.AlterField(
            model_name='registro',
            name='ciudad',
            field=models.CharField(choices=[('girardot', 'girardot'), ('leticia', 'leticia'), ('apartado', 'apartado'), ('tunja', 'tunja'), ('bogota', 'bogota'), ('cucuta', 'cucuta'), ('turbo', 'turbo'), ('cartagena', 'cartagena'), ('facatativa', 'facatativa'), ('fusagasuga', 'fusagasuga'), ('cali', 'cali'), ('zipaquira', 'zipaquira'), ('medellin', 'medellin'), ('sabanalarga', 'sabanalarga'), ('boyaca', 'boyaca'), ('el carmen de bolivar', 'el carmen de bolivar'), ('barranquilla', 'barranquilla'), ('magangue', 'magangue'), ('arauca', 'arauca'), ('caucasia', 'caucasia'), ('rionegro', 'rionegro')], max_length=40),
        ),
        migrations.AlterModelTable(
            name='inventario',
            table='inventario',
        ),
    ]
