# Generated by Django 4.1.3 on 2022-12-08 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0020_alter_inventario_cantidad_alter_inventario_ciudad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='cantidad',
            field=models.CharField(choices=[('100 kgs', '100 kgs'), ('70 kgs', '70 kgs'), ('80 kgs', '80 kgs'), ('60 kgs', '60 kgs'), ('50 kgs', '50 kgs'), ('90 kgs', '90 kgs')], max_length=254),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='ciudad',
            field=models.CharField(choices=[('girardot', 'girardot'), ('bogota', 'bogota'), ('caucasia', 'caucasia'), ('tunja', 'tunja'), ('el carmen de bolivar', 'el carmen de bolivar'), ('sabanalarga', 'sabanalarga'), ('rionegro', 'rionegro'), ('medellin', 'medellin'), ('leticia', 'leticia'), ('boyaca', 'boyaca'), ('cartagena', 'cartagena'), ('barranquilla', 'barranquilla'), ('turbo', 'turbo'), ('cucuta', 'cucuta'), ('fusagasuga', 'fusagasuga'), ('arauca', 'arauca'), ('facatativa', 'facatativa'), ('apartado', 'apartado'), ('cali', 'cali'), ('zipaquira', 'zipaquira'), ('magangue', 'magangue')], max_length=254),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='estado',
            field=models.CharField(choices=[('no disponible', 'no disponible'), ('Disponible', 'disponible'), ('pendiente', 'pendiente')], max_length=254),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='producto',
            field=models.CharField(choices=[('papaya', 'papaya'), ('mandarina', 'mandarina'), ('banano', 'banano'), ('fresa', 'fresa'), ('manzana', 'manzana'), ('uvas', 'uvas')], max_length=254),
        ),
        migrations.AlterField(
            model_name='productos',
            name='cantidad',
            field=models.CharField(choices=[('100 kgs', '100 kgs'), ('70 kgs', '70 kgs'), ('80 kgs', '80 kgs'), ('60 kgs', '60 kgs'), ('50 kgs', '50 kgs'), ('90 kgs', '90 kgs')], max_length=254),
        ),
        migrations.AlterField(
            model_name='productos',
            name='ciudad',
            field=models.CharField(choices=[('girardot', 'girardot'), ('bogota', 'bogota'), ('caucasia', 'caucasia'), ('tunja', 'tunja'), ('el carmen de bolivar', 'el carmen de bolivar'), ('sabanalarga', 'sabanalarga'), ('rionegro', 'rionegro'), ('medellin', 'medellin'), ('leticia', 'leticia'), ('boyaca', 'boyaca'), ('cartagena', 'cartagena'), ('barranquilla', 'barranquilla'), ('turbo', 'turbo'), ('cucuta', 'cucuta'), ('fusagasuga', 'fusagasuga'), ('arauca', 'arauca'), ('facatativa', 'facatativa'), ('apartado', 'apartado'), ('cali', 'cali'), ('zipaquira', 'zipaquira'), ('magangue', 'magangue')], max_length=254),
        ),
        migrations.AlterField(
            model_name='productos',
            name='estado',
            field=models.CharField(choices=[('no disponible', 'no disponible'), ('Disponible', 'disponible'), ('pendiente', 'pendiente')], max_length=254),
        ),
        migrations.AlterField(
            model_name='productos',
            name='producto',
            field=models.CharField(choices=[('papaya', 'papaya'), ('mandarina', 'mandarina'), ('banano', 'banano'), ('fresa', 'fresa'), ('manzana', 'manzana'), ('uvas', 'uvas')], max_length=254),
        ),
        migrations.AlterField(
            model_name='registro',
            name='ciudad',
            field=models.CharField(choices=[('girardot', 'girardot'), ('bogota', 'bogota'), ('caucasia', 'caucasia'), ('tunja', 'tunja'), ('el carmen de bolivar', 'el carmen de bolivar'), ('sabanalarga', 'sabanalarga'), ('rionegro', 'rionegro'), ('medellin', 'medellin'), ('leticia', 'leticia'), ('boyaca', 'boyaca'), ('cartagena', 'cartagena'), ('barranquilla', 'barranquilla'), ('turbo', 'turbo'), ('cucuta', 'cucuta'), ('fusagasuga', 'fusagasuga'), ('arauca', 'arauca'), ('facatativa', 'facatativa'), ('apartado', 'apartado'), ('cali', 'cali'), ('zipaquira', 'zipaquira'), ('magangue', 'magangue')], max_length=40),
        ),
        migrations.AlterField(
            model_name='registro',
            name='rol',
            field=models.CharField(choices=[('eres conductor', 'eres conducto'), ('eres cliente', 'eres cliente'), ('eres productor', 'eres productor')], max_length=254),
        ),
    ]
