# Generated by Django 4.1.3 on 2022-12-08 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0022_alter_inventario_cantidad_alter_inventario_ciudad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='cantidad',
            field=models.CharField(choices=[('50 kgs', '50 kgs'), ('60 kgs', '60 kgs'), ('80 kgs', '80 kgs'), ('90 kgs', '90 kgs'), ('100 kgs', '100 kgs'), ('70 kgs', '70 kgs')], max_length=254),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='ciudad',
            field=models.CharField(choices=[('apartado', 'apartado'), ('sabanalarga', 'sabanalarga'), ('boyaca', 'boyaca'), ('el carmen de bolivar', 'el carmen de bolivar'), ('cali', 'cali'), ('caucasia', 'caucasia'), ('arauca', 'arauca'), ('zipaquira', 'zipaquira'), ('leticia', 'leticia'), ('tunja', 'tunja'), ('cartagena', 'cartagena'), ('bogota', 'bogota'), ('girardot', 'girardot'), ('fusagasuga', 'fusagasuga'), ('medellin', 'medellin'), ('facatativa', 'facatativa'), ('magangue', 'magangue'), ('turbo', 'turbo'), ('cucuta', 'cucuta'), ('rionegro', 'rionegro'), ('barranquilla', 'barranquilla')], max_length=254),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='ofrece_transporte',
            field=models.CharField(choices=[('NO', 'NO'), ('SI', 'SI')], max_length=254),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='producto',
            field=models.CharField(choices=[('uvas', 'uvas'), ('mandarina', 'mandarina'), ('manzana', 'manzana'), ('banano', 'banano'), ('fresa', 'fresa'), ('papaya', 'papaya')], max_length=254),
        ),
        migrations.AlterField(
            model_name='productos',
            name='cantidad',
            field=models.CharField(choices=[('50 kgs', '50 kgs'), ('60 kgs', '60 kgs'), ('80 kgs', '80 kgs'), ('90 kgs', '90 kgs'), ('100 kgs', '100 kgs'), ('70 kgs', '70 kgs')], max_length=254),
        ),
        migrations.AlterField(
            model_name='productos',
            name='ciudad',
            field=models.CharField(choices=[('apartado', 'apartado'), ('sabanalarga', 'sabanalarga'), ('boyaca', 'boyaca'), ('el carmen de bolivar', 'el carmen de bolivar'), ('cali', 'cali'), ('caucasia', 'caucasia'), ('arauca', 'arauca'), ('zipaquira', 'zipaquira'), ('leticia', 'leticia'), ('tunja', 'tunja'), ('cartagena', 'cartagena'), ('bogota', 'bogota'), ('girardot', 'girardot'), ('fusagasuga', 'fusagasuga'), ('medellin', 'medellin'), ('facatativa', 'facatativa'), ('magangue', 'magangue'), ('turbo', 'turbo'), ('cucuta', 'cucuta'), ('rionegro', 'rionegro'), ('barranquilla', 'barranquilla')], max_length=254),
        ),
        migrations.AlterField(
            model_name='productos',
            name='ofrece_transporte',
            field=models.CharField(choices=[('NO', 'NO'), ('SI', 'SI')], max_length=254),
        ),
        migrations.AlterField(
            model_name='productos',
            name='producto',
            field=models.CharField(choices=[('uvas', 'uvas'), ('mandarina', 'mandarina'), ('manzana', 'manzana'), ('banano', 'banano'), ('fresa', 'fresa'), ('papaya', 'papaya')], max_length=254),
        ),
        migrations.AlterField(
            model_name='registro',
            name='ciudad',
            field=models.CharField(choices=[('apartado', 'apartado'), ('sabanalarga', 'sabanalarga'), ('boyaca', 'boyaca'), ('el carmen de bolivar', 'el carmen de bolivar'), ('cali', 'cali'), ('caucasia', 'caucasia'), ('arauca', 'arauca'), ('zipaquira', 'zipaquira'), ('leticia', 'leticia'), ('tunja', 'tunja'), ('cartagena', 'cartagena'), ('bogota', 'bogota'), ('girardot', 'girardot'), ('fusagasuga', 'fusagasuga'), ('medellin', 'medellin'), ('facatativa', 'facatativa'), ('magangue', 'magangue'), ('turbo', 'turbo'), ('cucuta', 'cucuta'), ('rionegro', 'rionegro'), ('barranquilla', 'barranquilla')], max_length=40),
        ),
        migrations.AlterField(
            model_name='registro',
            name='rol',
            field=models.CharField(choices=[('eres conductor', 'eres conducto'), ('eres cliente', 'eres cliente'), ('eres productor', 'eres productor')], max_length=254),
        ),
    ]
