# Generated by Django 4.1.3 on 2022-12-08 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0023_alter_inventario_cantidad_alter_inventario_ciudad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='cantidad',
            field=models.CharField(choices=[('70 kgs', '70 kgs'), ('80 kgs', '80 kgs'), ('90 kgs', '90 kgs'), ('50 kgs', '50 kgs'), ('100 kgs', '100 kgs'), ('60 kgs', '60 kgs')], max_length=254),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='ciudad',
            field=models.CharField(choices=[('sabanalarga', 'sabanalarga'), ('cucuta', 'cucuta'), ('boyaca', 'boyaca'), ('arauca', 'arauca'), ('apartado', 'apartado'), ('bogota', 'bogota'), ('el carmen de bolivar', 'el carmen de bolivar'), ('facatativa', 'facatativa'), ('cartagena', 'cartagena'), ('barranquilla', 'barranquilla'), ('caucasia', 'caucasia'), ('zipaquira', 'zipaquira'), ('fusagasuga', 'fusagasuga'), ('cali', 'cali'), ('tunja', 'tunja'), ('medellin', 'medellin'), ('girardot', 'girardot'), ('turbo', 'turbo'), ('leticia', 'leticia'), ('rionegro', 'rionegro'), ('magangue', 'magangue')], max_length=254),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='estado',
            field=models.CharField(choices=[('Disponible', 'disponible'), ('no disponible', 'no disponible'), ('pendiente', 'pendiente')], max_length=254),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='ofrece_transporte',
            field=models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], max_length=254),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='producto',
            field=models.CharField(choices=[('banano', 'banano'), ('mandarina', 'mandarina'), ('manzana', 'manzana'), ('uvas', 'uvas'), ('papaya', 'papaya'), ('fresa', 'fresa')], max_length=254),
        ),
        migrations.AlterField(
            model_name='productos',
            name='cantidad',
            field=models.CharField(choices=[('70 kgs', '70 kgs'), ('80 kgs', '80 kgs'), ('90 kgs', '90 kgs'), ('50 kgs', '50 kgs'), ('100 kgs', '100 kgs'), ('60 kgs', '60 kgs')], max_length=254),
        ),
        migrations.AlterField(
            model_name='productos',
            name='ciudad',
            field=models.CharField(choices=[('sabanalarga', 'sabanalarga'), ('cucuta', 'cucuta'), ('boyaca', 'boyaca'), ('arauca', 'arauca'), ('apartado', 'apartado'), ('bogota', 'bogota'), ('el carmen de bolivar', 'el carmen de bolivar'), ('facatativa', 'facatativa'), ('cartagena', 'cartagena'), ('barranquilla', 'barranquilla'), ('caucasia', 'caucasia'), ('zipaquira', 'zipaquira'), ('fusagasuga', 'fusagasuga'), ('cali', 'cali'), ('tunja', 'tunja'), ('medellin', 'medellin'), ('girardot', 'girardot'), ('turbo', 'turbo'), ('leticia', 'leticia'), ('rionegro', 'rionegro'), ('magangue', 'magangue')], max_length=254),
        ),
        migrations.AlterField(
            model_name='productos',
            name='estado',
            field=models.CharField(choices=[('Disponible', 'disponible'), ('no disponible', 'no disponible'), ('pendiente', 'pendiente')], max_length=254),
        ),
        migrations.AlterField(
            model_name='productos',
            name='ofrece_transporte',
            field=models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], max_length=254),
        ),
        migrations.AlterField(
            model_name='productos',
            name='producto',
            field=models.CharField(choices=[('banano', 'banano'), ('mandarina', 'mandarina'), ('manzana', 'manzana'), ('uvas', 'uvas'), ('papaya', 'papaya'), ('fresa', 'fresa')], max_length=254),
        ),
        migrations.AlterField(
            model_name='registro',
            name='ciudad',
            field=models.CharField(choices=[('sabanalarga', 'sabanalarga'), ('cucuta', 'cucuta'), ('boyaca', 'boyaca'), ('arauca', 'arauca'), ('apartado', 'apartado'), ('bogota', 'bogota'), ('el carmen de bolivar', 'el carmen de bolivar'), ('facatativa', 'facatativa'), ('cartagena', 'cartagena'), ('barranquilla', 'barranquilla'), ('caucasia', 'caucasia'), ('zipaquira', 'zipaquira'), ('fusagasuga', 'fusagasuga'), ('cali', 'cali'), ('tunja', 'tunja'), ('medellin', 'medellin'), ('girardot', 'girardot'), ('turbo', 'turbo'), ('leticia', 'leticia'), ('rionegro', 'rionegro'), ('magangue', 'magangue')], max_length=40),
        ),
        migrations.AlterField(
            model_name='registro',
            name='rol',
            field=models.CharField(choices=[('eres productor', 'eres productor'), ('eres conductor', 'eres conducto'), ('eres cliente', 'eres cliente')], max_length=254),
        ),
    ]
