# Generated by Django 4.1.3 on 2022-12-09 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0025_delete_frutas_delete_granos_delete_inventario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(choices=[('manzana', 'manzana'), ('banano', 'banano'), ('mandarina', 'mandarina'), ('uvas', 'uvas'), ('papaya', 'papaya'), ('fresa', 'fresa')], max_length=254)),
                ('cantidad', models.CharField(choices=[('100 kgs', '100 kgs'), ('50 kgs', '50 kgs'), ('80 kgs', '80 kgs'), ('60 kgs', '60 kgs'), ('90 kgs', '90 kgs'), ('70 kgs', '70 kgs')], max_length=254)),
                ('precio_kgs', models.CharField(max_length=254)),
                ('precio_total', models.CharField(max_length=254)),
                ('ciudad', models.CharField(choices=[('bogota', 'bogota'), ('el carmen de bolivar', 'el carmen de bolivar'), ('sabanalarga', 'sabanalarga'), ('arauca', 'arauca'), ('magangue', 'magangue'), ('turbo', 'turbo'), ('boyaca', 'boyaca'), ('cali', 'cali'), ('cartagena', 'cartagena'), ('fusagasuga', 'fusagasuga'), ('medellin', 'medellin'), ('caucasia', 'caucasia'), ('facatativa', 'facatativa'), ('tunja', 'tunja'), ('barranquilla', 'barranquilla'), ('leticia', 'leticia'), ('apartado', 'apartado'), ('cucuta', 'cucuta'), ('zipaquira', 'zipaquira'), ('rionegro', 'rionegro'), ('girardot', 'girardot')], max_length=254)),
                ('fecha_disponible', models.CharField(max_length=254)),
                ('ofrece_transporte', models.CharField(choices=[('NO', 'NO'), ('SI', 'SI')], max_length=254)),
                ('descripcion', models.CharField(max_length=254)),
                ('estado', models.CharField(choices=[('Disponible', 'disponible'), ('pendiente', 'pendiente'), ('no disponible', 'no disponible')], max_length=254)),
            ],
            options={
                'db_table': 'inventario',
            },
        ),
        migrations.AlterField(
            model_name='registro',
            name='ciudad',
            field=models.CharField(choices=[('bogota', 'bogota'), ('el carmen de bolivar', 'el carmen de bolivar'), ('sabanalarga', 'sabanalarga'), ('arauca', 'arauca'), ('magangue', 'magangue'), ('turbo', 'turbo'), ('boyaca', 'boyaca'), ('cali', 'cali'), ('cartagena', 'cartagena'), ('fusagasuga', 'fusagasuga'), ('medellin', 'medellin'), ('caucasia', 'caucasia'), ('facatativa', 'facatativa'), ('tunja', 'tunja'), ('barranquilla', 'barranquilla'), ('leticia', 'leticia'), ('apartado', 'apartado'), ('cucuta', 'cucuta'), ('zipaquira', 'zipaquira'), ('rionegro', 'rionegro'), ('girardot', 'girardot')], max_length=40),
        ),
        migrations.AlterField(
            model_name='registro',
            name='rol',
            field=models.CharField(choices=[('eres cliente', 'eres cliente'), ('eres conductor', 'eres conducto'), ('eres productor', 'eres productor')], max_length=254),
        ),
    ]
