# Generated by Django 4.1.3 on 2022-12-09 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0026_inventario_alter_registro_ciudad_alter_registro_rol'),
    ]

    operations = [
        migrations.CreateModel(
            name='productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(choices=[('banano', 'banano'), ('mandarina', 'mandarina'), ('papaya', 'papaya'), ('uvas', 'uvas'), ('manzana', 'manzana'), ('fresa', 'fresa')], max_length=254)),
                ('cantidad', models.CharField(choices=[('100 kgs', '100 kgs'), ('70 kgs', '70 kgs'), ('60 kgs', '60 kgs'), ('90 kgs', '90 kgs'), ('80 kgs', '80 kgs'), ('50 kgs', '50 kgs')], max_length=254)),
                ('precio_kgs', models.CharField(max_length=254)),
                ('precio_total', models.CharField(max_length=254)),
                ('ciudad', models.CharField(choices=[('fusagasuga', 'fusagasuga'), ('caucasia', 'caucasia'), ('cartagena', 'cartagena'), ('rionegro', 'rionegro'), ('barranquilla', 'barranquilla'), ('girardot', 'girardot'), ('cucuta', 'cucuta'), ('medellin', 'medellin'), ('arauca', 'arauca'), ('tunja', 'tunja'), ('bogota', 'bogota'), ('leticia', 'leticia'), ('sabanalarga', 'sabanalarga'), ('apartado', 'apartado'), ('zipaquira', 'zipaquira'), ('magangue', 'magangue'), ('boyaca', 'boyaca'), ('el carmen de bolivar', 'el carmen de bolivar'), ('turbo', 'turbo'), ('facatativa', 'facatativa'), ('cali', 'cali')], max_length=254)),
                ('fecha_disponible', models.CharField(max_length=254)),
                ('ofrece_transporte', models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], max_length=254)),
                ('descripcion', models.CharField(max_length=254)),
                ('estado', models.CharField(choices=[('no disponible', 'no disponible'), ('Disponible', 'disponible'), ('pendiente', 'pendiente')], max_length=254)),
            ],
            options={
                'db_table': 'productos',
            },
        ),
        migrations.AlterField(
            model_name='inventario',
            name='cantidad',
            field=models.CharField(choices=[('100 kgs', '100 kgs'), ('70 kgs', '70 kgs'), ('60 kgs', '60 kgs'), ('90 kgs', '90 kgs'), ('80 kgs', '80 kgs'), ('50 kgs', '50 kgs')], max_length=254),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='ciudad',
            field=models.CharField(choices=[('fusagasuga', 'fusagasuga'), ('caucasia', 'caucasia'), ('cartagena', 'cartagena'), ('rionegro', 'rionegro'), ('barranquilla', 'barranquilla'), ('girardot', 'girardot'), ('cucuta', 'cucuta'), ('medellin', 'medellin'), ('arauca', 'arauca'), ('tunja', 'tunja'), ('bogota', 'bogota'), ('leticia', 'leticia'), ('sabanalarga', 'sabanalarga'), ('apartado', 'apartado'), ('zipaquira', 'zipaquira'), ('magangue', 'magangue'), ('boyaca', 'boyaca'), ('el carmen de bolivar', 'el carmen de bolivar'), ('turbo', 'turbo'), ('facatativa', 'facatativa'), ('cali', 'cali')], max_length=254),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='estado',
            field=models.CharField(choices=[('no disponible', 'no disponible'), ('Disponible', 'disponible'), ('pendiente', 'pendiente')], max_length=254),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='ofrece_transporte',
            field=models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], max_length=254),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='producto',
            field=models.CharField(choices=[('banano', 'banano'), ('mandarina', 'mandarina'), ('papaya', 'papaya'), ('uvas', 'uvas'), ('manzana', 'manzana'), ('fresa', 'fresa')], max_length=254),
        ),
        migrations.AlterField(
            model_name='registro',
            name='ciudad',
            field=models.CharField(choices=[('fusagasuga', 'fusagasuga'), ('caucasia', 'caucasia'), ('cartagena', 'cartagena'), ('rionegro', 'rionegro'), ('barranquilla', 'barranquilla'), ('girardot', 'girardot'), ('cucuta', 'cucuta'), ('medellin', 'medellin'), ('arauca', 'arauca'), ('tunja', 'tunja'), ('bogota', 'bogota'), ('leticia', 'leticia'), ('sabanalarga', 'sabanalarga'), ('apartado', 'apartado'), ('zipaquira', 'zipaquira'), ('magangue', 'magangue'), ('boyaca', 'boyaca'), ('el carmen de bolivar', 'el carmen de bolivar'), ('turbo', 'turbo'), ('facatativa', 'facatativa'), ('cali', 'cali')], max_length=40),
        ),
        migrations.AlterField(
            model_name='registro',
            name='rol',
            field=models.CharField(choices=[('eres cliente', 'eres cliente'), ('eres productor', 'eres productor'), ('eres conductor', 'eres conducto')], max_length=254),
        ),
    ]
